import type { AuditAnswers, AuditObservation, PageSignals } from "./types";

const page = (overrides: Partial<PageSignals> & Pick<PageSignals, "url" | "pageType" | "title">): PageSignals => ({
  finalUrl: overrides.url,
  status: 200,
  contentType: "text/html; charset=utf-8",
  titleLength: overrides.title.length,
  description: "Practical operations consulting for growing industrial teams that need calmer systems and measurable results.",
  descriptionLength: 108,
  canonical: overrides.url,
  robots: "index, follow",
  htmlLang: "en",
  hasViewport: true,
  h1Count: 1,
  h1Text: "Make complex operations easier to run",
  headings: [
    { level: 1, text: "Make complex operations easier to run" },
    { level: 2, text: "What we help improve" },
    { level: 2, text: "A practical way forward" },
  ],
  headingSkips: 0,
  wordCount: 420,
  sectionCount: 5,
  linkCount: 14,
  internalLinkCount: 9,
  unclearLinkCount: 2,
  brokenAnchorCount: 0,
  imageCount: 5,
  imagesWithAlt: 3,
  controlCount: 1,
  namedControlCount: 1,
  formCount: 0,
  jsonLdCount: 1,
  jsonLdValidCount: 1,
  schemaTypes: ["Organization"],
  hasOrganizationSchema: true,
  hasServiceSchema: false,
  hasAuthorSignal: false,
  hasAddressSignal: true,
  hasContactSignal: true,
  hasCtaSignal: true,
  ctaLabels: ["Talk with our team", "Explore services"],
  actionableCtaLabels: ["Talk with our team"],
  ctaTargets: [{ label: "Talk with our team", destination: new URL("/contact", overrides.url).toString(), kind: "link" }],
  hasTrustSignal: false,
  hasServiceLanguage: true,
  hasEntityLanguage: true,
  hasAudienceLanguage: true,
  directAnswerCount: 1,
  visibleContentLength: 2580,
  ...overrides,
});

export const SAMPLE_ANSWERS: AuditAnswers = {
  businessType: "b2b",
  audience: "Operations leaders at growing industrial companies",
  purpose: "generate-leads",
  conversionAction: "contact",
  differentiation: "unsure",
  expectedResults: "no",
  lastReviewed: "one-year",
};

export const SAMPLE_OBSERVATION: AuditObservation = {
  auditId: "sample-working-with-friction",
  requestedUrl: "https://northstar-operations.example/",
  finalUrl: "https://northstar-operations.example/",
  normalizedDomain: "northstar-operations.example",
  createdAt: "2026-08-19T15:00:00.000Z",
  detectedLanguage: "en",
  sample: true,
  provenance: { source: "demo-fixture", crawlerVersion: "representative-fixture-v1", rulesetVersion: "lv-website-opportunity-v1" },
  answers: SAMPLE_ANSWERS,
  cached: false,
  discoveredPageCount: 5,
  failedPageCount: 0,
  warnings: [],
  lab: {
    measured: true,
    performanceScore: 68,
    accessibilityScore: 88,
    bestPracticesScore: 93,
    seoScore: 86,
    lcpMs: 3180,
    cls: 0.07,
    tbtMs: 240,
    source: "pagespeed",
  },
  pages: [
    page({
      url: "https://northstar-operations.example/",
      pageType: "submitted",
      title: "Northstar Operations | Industrial Operations Consulting",
      description: "Operations consulting for growing industrial teams.",
      descriptionLength: 52,
      h1Text: "Make complex operations easier to run",
      hasTrustSignal: false,
      directAnswerCount: 1,
    }),
    page({
      url: "https://northstar-operations.example/services",
      pageType: "service",
      title: "Operations Consulting Services | Northstar",
      h1Text: "Operations consulting built around the work",
      hasServiceSchema: true,
      schemaTypes: ["Service"],
      hasTrustSignal: false,
      directAnswerCount: 2,
      imageCount: 3,
      imagesWithAlt: 2,
    }),
    page({
      url: "https://northstar-operations.example/about",
      pageType: "about",
      title: "About Northstar Operations",
      h1Text: "A calmer way to improve complex operations",
      hasAuthorSignal: true,
      hasTrustSignal: true,
      directAnswerCount: 1,
      unclearLinkCount: 0,
    }),
    page({
      url: "https://northstar-operations.example/contact",
      pageType: "contact",
      title: "Talk With Northstar Operations",
      h1Text: "Tell us what is getting in the way",
      formCount: 1,
      controlCount: 6,
      namedControlCount: 5,
      hasTrustSignal: false,
      directAnswerCount: 0,
    }),
    page({
      url: "https://northstar-operations.example/insights/reduce-changeover-time",
      pageType: "resource",
      title: "How to Reduce Changeover Time | Northstar Operations",
      h1Text: "How to reduce changeover time without creating more work",
      hasAuthorSignal: true,
      hasTrustSignal: true,
      directAnswerCount: 3,
      wordCount: 980,
      visibleContentLength: 6120,
      imageCount: 4,
      imagesWithAlt: 4,
    }),
  ],
};
