import { createContext, ReactNode, useContext, useEffect, useMemo, useState } from "react";

export type Language = "en" | "es";

const LANGUAGE_STORAGE_KEY = "lv-marketing-suite-language";

const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    "common.cancel": "Cancel",
    "common.copy": "Copy",
    "common.loading": "Loading...",
    "common.new": "New",
    "common.save": "Save",
    "common.send": "Send",
    "common.status": "Status",
    "language.label": "Language",
    "language.english": "English",
    "language.spanish": "Spanish",
    "language.short.en": "EN",
    "language.short.es": "ES",
    "nav.dashboard": "Dashboard",
    "nav.skills": "Skills",
    "nav.projects": "Projects",
    "nav.workspace": "Workspace",
    "nav.contacts": "Contacts",
    "nav.intake": "Intake",
    "nav.campaigns": "Campaigns",
    "nav.photoSessions": "Photo Sessions",
    "nav.fileDrop": "File Drop",
    "nav.history": "History",
    "nav.settings": "Settings",
    "dashboard.greeting": "Hey {{name}}",
    "dashboard.subtitle": "Here's your marketing workspace.",
    "dashboard.totalOutputs": "Total Outputs",
    "dashboard.activeProjects": "Active Projects",
    "dashboard.skillsAvailable": "Skills Available",
    "dashboard.thisWeek": "This Week",
    "dashboard.quickStart": "Quick Start",
    "dashboard.viewAllSkills": "View all skills",
    "dashboard.recentOutputs": "Recent Outputs",
    "dashboard.viewAll": "View all",
    "dashboard.noOutputs": "No outputs yet. Run a skill to get started!",
    "dashboard.noProjects": "No active projects. Create one to organize your outputs.",
    "skills.title": "Skills Library",
    "skills.subtitle": "{{count}} AI-powered marketing skills",
    "skills.all": "All",
    "skills.tip": "Tip:",
    "skills.tipLead": "Set up a",
    "skills.tipAction": "Project Marketing Context",
    "skills.tipSuffix": "to get better, more personalized outputs from every skill.",
    "skills.searchPlaceholder": "Search skills...",
    "skills.noMatch": "No skills match your search.",
    "skills.setupFirst": "Setup First",
    "skills.noContext": "No context",
    "skills.notFound": "Skill not found.",
    "skills.backToLibrary": "Back to Skills Library",
    "skills.back": "Skills",
    "skills.projectOptional": "Project (optional)",
    "skills.selectProject": "Select a project...",
    "skills.noProject": "No project",
    "skills.noMarketingContext": "No marketing context set up for this project.",
    "skills.contextWillBeUsed": "Marketing context will be used automatically.",
    "skills.selectPlaceholder": "Select...",
    "skills.required": "{{label}} is required",
    "skills.running": "Running...",
    "skills.run": "Run Skill",
    "skills.emptyState": "Fill in the context form and click {{action}} to get AI-generated {{skill}} output.",
    "skills.copied": "Copied to clipboard!",
    "skills.outputSaved": "Output saved!",
    "skills.continuationSaved": "Continuation saved!",
    "skills.newRun": "New Run",
    "skills.followUpPlaceholder": "Ask a follow-up question...",
    "skills.continuePlaceholder": "Continue the conversation with {{skill}}... (Cmd+Enter to send)",
    "skills.theAI": "the AI",
    "skills.saveThis": "Save this",
    "skills.saveLatest": "Save latest",
    "skills.saveOutput": "Save Output",
    "skills.outputTitle": "Title",
    "skills.outputTitlePlaceholder": "Give this output a name...",
    "skills.outputNotFound": "Output not found.",
    "skills.deleteOutputConfirm": "Delete this output?",
    "skills.deleteOutputConfirmLong": "Delete this output? This cannot be undone.",
    "skills.openFullPage": "Open full page",
    "history.title": "Output History",
    "history.subtitle": "{{count}} output{{suffix}}",
    "history.searchPlaceholder": "Search outputs...",
    "history.allProjects": "All projects",
    "history.allSkills": "All skills",
    "history.noFilterMatch": "No outputs match your filters.",
    "history.noSaved": "No outputs saved yet. Run a skill and save your results!",
    "settings.title": "Settings",
    "settings.account": "Account",
    "settings.organization": "Organization",
    "settings.branches": "Branches",
    "settings.team": "Team",
    "settings.activity": "Activity",
    "settings.name": "Name",
    "settings.organizationId": "Organization ID",
    "settings.profileHelp": "To update your name or email, contact your workspace administrator.",
    "settings.languagePreference": "Language preference",
    "settings.languageHelp": "Choose the language used across the main app controls.",
    "settings.teamMembers": "Team Members",
    "settings.pendingInvitations": "Pending Invitations",
    "settings.inviteTeamMember": "Invite Team Member",
    "settings.noMembers": "No members yet.",
    "settings.noPendingInvitations": "No pending invitations.",
    "settings.featureAccess": "Feature Access",
    "settings.sendInvite": "Send Invite",
    "settings.loadingMembers": "Loading members...",
    "branches.title": "LATAM Branches",
    "branches.subtitle": "Add expansion branches as tenants under HQ oversight. HQ keeps visibility into branch status and activity.",
    "branches.add": "Add Branch",
    "branches.addFirst": "Add the first branch to prepare the LATAM rollout.",
    "branches.branchName": "Branch name",
    "branches.code": "Branch code",
    "branches.country": "Country",
    "branches.countryFlag": "Country flag",
    "branches.countryFlagPlaceholder": "Optional flag",
    "branches.city": "City",
    "branches.timezone": "Timezone reference",
    "branches.localTime": "Local time",
    "branches.notificationBanner": "Branch bulletin",
    "branches.notificationPlaceholder": "Add a short message local team members should see.",
    "branches.noNotification": "No branch bulletin yet.",
    "branches.profileUpdated": "Branch profile updated.",
    "branches.profileUpdateFailed": "Failed to update branch profile",
    "branches.primaryLanguage": "Primary language",
    "branches.region": "Operating region",
    "branches.hqMonitored": "HQ monitored",
    "branches.hqMonitoredHelp": "HQ monitoring stays enabled for every branch so central leadership can govern expansion.",
    "branches.namePlaceholder": "LV Branding Mexico City",
    "branches.codePlaceholder": "MX-CDMX",
    "branches.countryPlaceholder": "Mexico",
    "branches.cityPlaceholder": "Mexico City",
    "branches.created": "Branch added under HQ monitoring.",
    "branches.createFailed": "Failed to add branch",
    "branches.statusUpdated": "Branch status updated.",
    "branches.statusUpdateFailed": "Failed to update branch status",
    "branches.status.planning": "Planning",
    "branches.status.active": "Active",
    "branches.status.paused": "Paused",
    "branches.status.archived": "Archived",
    "branches.language.en": "English",
    "branches.language.es": "Spanish",
    "branches.noCode": "No code",
    "branches.noCity": "City pending",
    "branches.loading": "Loading branches...",
    "branches.team": "Branch team",
    "branches.addTeamMember": "Add to branch",
    "branches.selectMember": "Select member",
    "branches.noTeam": "No branch team assigned yet.",
    "branches.teamAdded": "Branch team member added.",
    "branches.teamUpdated": "Branch team role updated.",
    "branches.teamRemoved": "Branch team member removed.",
    "branches.teamAddFailed": "Failed to add branch team member",
    "branches.teamUpdateFailed": "Failed to update branch team role",
    "branches.teamRemoveFailed": "Failed to remove branch team member",
    "branches.role.regional_ceo": "Local CEO",
    "branches.role.manager": "Manager",
    "branches.role.crew": "Member",
    "settings.hqTeam": "HQ Team",
    "settings.branchTeams": "Branch Teams",
    "settings.branchTeamsMeta": "{{members}} members across {{branches}} branches",
    "settings.noBranchTeamsYet": "No branch team members yet. Invite from the Branches tab.",
    "settings.noActiveMembersYet": "No active members yet.",
    "settings.pendingInvitesCount": "{{count}} pending",
    "activity.created_branch": "Created branch",
    "activity.updated_branch_status": "Updated branch status",
  },
  es: {
    "common.cancel": "Cancelar",
    "common.copy": "Copiar",
    "common.loading": "Cargando...",
    "common.new": "Nuevo",
    "common.save": "Guardar",
    "common.send": "Enviar",
    "common.status": "Estado",
    "language.label": "Idioma",
    "language.english": "Inglés",
    "language.spanish": "Español",
    "language.short.en": "EN",
    "language.short.es": "ES",
    "nav.dashboard": "Panel",
    "nav.skills": "Habilidades",
    "nav.projects": "Proyectos",
    "nav.workspace": "Espacio",
    "nav.contacts": "Contactos",
    "nav.intake": "Formulario",
    "nav.campaigns": "Campañas",
    "nav.photoSessions": "Sesiones de Fotos",
    "nav.fileDrop": "Archivos",
    "nav.history": "Historial",
    "nav.settings": "Configuración",
    "dashboard.greeting": "Hola {{name}}",
    "dashboard.subtitle": "Este es tu espacio de marketing.",
    "dashboard.totalOutputs": "Resultados Totales",
    "dashboard.activeProjects": "Proyectos Activos",
    "dashboard.skillsAvailable": "Habilidades",
    "dashboard.thisWeek": "Esta Semana",
    "dashboard.quickStart": "Inicio Rápido",
    "dashboard.viewAllSkills": "Ver habilidades",
    "dashboard.recentOutputs": "Resultados Recientes",
    "dashboard.viewAll": "Ver todo",
    "dashboard.noOutputs": "Todavía no hay resultados. Ejecuta una habilidad para comenzar.",
    "dashboard.noProjects": "No hay proyectos activos. Crea uno para organizar tus resultados.",
    "skills.title": "Biblioteca de Habilidades",
    "skills.subtitle": "{{count}} habilidades de marketing con IA",
    "skills.all": "Todas",
    "skills.tip": "Consejo:",
    "skills.tipLead": "Configura un",
    "skills.tipAction": "Contexto de Marketing del Proyecto",
    "skills.tipSuffix": "para obtener resultados mejores y mas personalizados en cada habilidad.",
    "skills.searchPlaceholder": "Buscar habilidades...",
    "skills.noMatch": "Ninguna habilidad coincide con tu busqueda.",
    "skills.setupFirst": "Configurar primero",
    "skills.noContext": "Sin contexto",
    "skills.notFound": "Habilidad no encontrada.",
    "skills.backToLibrary": "Volver a Habilidades",
    "skills.back": "Habilidades",
    "skills.projectOptional": "Proyecto (opcional)",
    "skills.selectProject": "Selecciona un proyecto...",
    "skills.noProject": "Sin proyecto",
    "skills.noMarketingContext": "No hay contexto de marketing configurado para este proyecto.",
    "skills.contextWillBeUsed": "El contexto de marketing se usara automaticamente.",
    "skills.selectPlaceholder": "Seleccionar...",
    "skills.required": "{{label}} es obligatorio",
    "skills.running": "Ejecutando...",
    "skills.run": "Ejecutar habilidad",
    "skills.emptyState": "Completa el formulario de contexto y haz clic en {{action}} para obtener un resultado de {{skill}} generado con IA.",
    "skills.copied": "Copiado al portapapeles.",
    "skills.outputSaved": "Resultado guardado.",
    "skills.continuationSaved": "Continuacion guardada.",
    "skills.newRun": "Nueva ejecucion",
    "skills.followUpPlaceholder": "Haz una pregunta de seguimiento...",
    "skills.continuePlaceholder": "Continua la conversacion con {{skill}}... (Cmd+Enter para enviar)",
    "skills.theAI": "la IA",
    "skills.saveThis": "Guardar esto",
    "skills.saveLatest": "Guardar lo ultimo",
    "skills.saveOutput": "Guardar Resultado",
    "skills.outputTitle": "Titulo",
    "skills.outputTitlePlaceholder": "Dale un nombre a este resultado...",
    "skills.outputNotFound": "Resultado no encontrado.",
    "skills.deleteOutputConfirm": "Eliminar este resultado?",
    "skills.deleteOutputConfirmLong": "Eliminar este resultado? Esta accion no se puede deshacer.",
    "skills.openFullPage": "Abrir pagina completa",
    "history.title": "Historial de Resultados",
    "history.subtitle": "{{count}} resultado{{suffix}}",
    "history.searchPlaceholder": "Buscar resultados...",
    "history.allProjects": "Todos los proyectos",
    "history.allSkills": "Todas las habilidades",
    "history.noFilterMatch": "Ningun resultado coincide con tus filtros.",
    "history.noSaved": "Todavia no hay resultados guardados. Ejecuta una habilidad y guarda tus resultados.",
    "settings.title": "Configuración",
    "settings.account": "Cuenta",
    "settings.organization": "Organización",
    "settings.branches": "Sucursales",
    "settings.team": "Equipo",
    "settings.activity": "Actividad",
    "settings.name": "Nombre",
    "settings.organizationId": "ID de Organización",
    "settings.profileHelp": "Para actualizar tu nombre o correo, contacta al administrador del espacio.",
    "settings.languagePreference": "Preferencia de idioma",
    "settings.languageHelp": "Elige el idioma usado en los controles principales de la app.",
    "settings.teamMembers": "Miembros del Equipo",
    "settings.pendingInvitations": "Invitaciones Pendientes",
    "settings.inviteTeamMember": "Invitar Miembro",
    "settings.noMembers": "Todavía no hay miembros.",
    "settings.noPendingInvitations": "No hay invitaciones pendientes.",
    "settings.featureAccess": "Acceso a Funciones",
    "settings.sendInvite": "Enviar Invitación",
    "settings.loadingMembers": "Cargando miembros...",
    "branches.title": "Sucursales LATAM",
    "branches.subtitle": "Agrega sucursales de expansión como tenants bajo supervisión de HQ. HQ conserva visibilidad sobre estado y actividad.",
    "branches.add": "Agregar Sucursal",
    "branches.addFirst": "Agrega la primera sucursal para preparar la expansión en LATAM.",
    "branches.branchName": "Nombre de sucursal",
    "branches.code": "Código de sucursal",
    "branches.country": "País",
    "branches.countryFlag": "Bandera del país",
    "branches.countryFlagPlaceholder": "Bandera opcional",
    "branches.city": "Ciudad",
    "branches.timezone": "Referencia horaria",
    "branches.localTime": "Hora local",
    "branches.notificationBanner": "Aviso de sucursal",
    "branches.notificationPlaceholder": "Agrega un mensaje breve para el equipo local.",
    "branches.noNotification": "Todavía no hay aviso de sucursal.",
    "branches.profileUpdated": "Perfil de sucursal actualizado.",
    "branches.profileUpdateFailed": "No se pudo actualizar el perfil de sucursal",
    "branches.primaryLanguage": "Idioma principal",
    "branches.region": "Región operativa",
    "branches.hqMonitored": "Monitoreada por HQ",
    "branches.hqMonitoredHelp": "El monitoreo de HQ permanece activo en cada sucursal para que liderazgo central gobierne la expansión.",
    "branches.namePlaceholder": "LV Branding Ciudad de México",
    "branches.codePlaceholder": "MX-CDMX",
    "branches.countryPlaceholder": "México",
    "branches.cityPlaceholder": "Ciudad de México",
    "branches.created": "Sucursal agregada bajo monitoreo de HQ.",
    "branches.createFailed": "No se pudo agregar la sucursal",
    "branches.statusUpdated": "Estado de sucursal actualizado.",
    "branches.statusUpdateFailed": "No se pudo actualizar el estado",
    "branches.status.planning": "Planeación",
    "branches.status.active": "Activa",
    "branches.status.paused": "Pausada",
    "branches.status.archived": "Archivada",
    "branches.language.en": "Inglés",
    "branches.language.es": "Español",
    "branches.noCode": "Sin código",
    "branches.noCity": "Ciudad pendiente",
    "branches.loading": "Cargando sucursales...",
    "branches.team": "Equipo de sucursal",
    "branches.addTeamMember": "Agregar a sucursal",
    "branches.selectMember": "Seleccionar miembro",
    "branches.noTeam": "Todavía no hay equipo asignado.",
    "branches.teamAdded": "Miembro agregado a la sucursal.",
    "branches.teamUpdated": "Rol de sucursal actualizado.",
    "branches.teamRemoved": "Miembro removido de la sucursal.",
    "branches.teamAddFailed": "No se pudo agregar el miembro a la sucursal",
    "branches.teamUpdateFailed": "No se pudo actualizar el rol de sucursal",
    "branches.teamRemoveFailed": "No se pudo remover el miembro de la sucursal",
    "branches.role.regional_ceo": "CEO Local",
    "branches.role.manager": "Gerente",
    "branches.role.crew": "Miembro",
    "settings.hqTeam": "Equipo HQ",
    "settings.branchTeams": "Equipos de Sucursal",
    "settings.branchTeamsMeta": "{{members}} miembros en {{branches}} sucursales",
    "settings.noBranchTeamsYet": "Todavía no hay miembros de sucursal. Invita desde la pestaña Sucursales.",
    "settings.noActiveMembersYet": "Todavía no hay miembros activos.",
    "settings.pendingInvitesCount": "{{count}} pendiente(s)",
    "activity.created_branch": "Creó sucursal",
    "activity.updated_branch_status": "Actualizó estado de sucursal",
  },
};

const LITERAL_TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {},
  es: {
    Settings: "Configuración",
    Dashboard: "Panel",
    "Here's your marketing workspace.": "Este es tu espacio de marketing.",
    "Skills Library": "Biblioteca de Habilidades",
    "33 AI-powered marketing skills": "33 habilidades de marketing con IA",
    Projects: "Proyectos",
    Contacts: "Contactos",
    "Houston MSA · brand-ready decision makers": "Houston MSA · decisores listos para marca",
    "Client Intake": "Formulario de Clientes",
    "Output History": "Historial de Resultados",
    "Email Campaigns": "Campañas de Email",
    "Compose, send and track email blasts": "Redacta, envía y mide campañas de email",
    "Photo Sessions": "Sesiones de Fotos",
    "Client File Drop": "Entrega de Archivos",
    "Send a link to clients so they can upload files directly to you.": "Envía un enlace para que los clientes suban archivos directamente.",
    Campaign: "Campaña",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, values?: Record<string, string | number>) => string;
  translateLiteral: (value?: string) => string | undefined;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

function getInitialLanguage(): Language {
  if (typeof window === "undefined") return "en";

  const stored = window.localStorage.getItem(LANGUAGE_STORAGE_KEY);
  if (stored === "en" || stored === "es") return stored;

  return window.navigator.language.toLowerCase().startsWith("es") ? "es" : "en";
}

function interpolate(value: string, values?: Record<string, string | number>) {
  if (!values) return value;
  return Object.entries(values).reduce(
    (result, [key, replacement]) => result.split(`{{${key}}}`).join(String(replacement)),
    value
  );
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(getInitialLanguage);

  useEffect(() => {
    window.localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo<LanguageContextType>(
    () => ({
      language,
      setLanguage: setLanguageState,
      t: (key, values) => interpolate(TRANSLATIONS[language][key] ?? TRANSLATIONS.en[key] ?? key, values),
      translateLiteral: (text) => {
        if (!text) return text;
        return LITERAL_TRANSLATIONS[language][text] ?? text;
      },
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
