import type { AuditCopy } from "./types.ts";

const rules: AuditCopy["rules"] = {
  "experience.mobileViewport": {
    title: "Mobile viewport",
    pass: "The analyzed pages tell mobile browsers how to size the experience.",
    partial: "Some pages are missing a reliable mobile viewport declaration.",
    fail: "The submitted experience does not declare a mobile viewport.",
    notMeasured: "Mobile viewport signals could not be measured.",
    recommendation: "Add one responsive viewport declaration to every page template.",
  },
  "experience.headingStructure": {
    title: "Heading structure",
    pass: "Headings create a clear, scannable hierarchy across the analyzed pages.",
    partial: "The heading hierarchy is useful in places but inconsistent across pages.",
    fail: "Visitors and assistive technology may struggle to understand the page hierarchy.",
    notMeasured: "Heading structure could not be measured.",
    recommendation: "Give each page one descriptive H1, then nest sections in a logical order.",
  },
  "experience.linkClarity": {
    title: "Link clarity",
    pass: "Most links explain where they lead and same-page targets resolve correctly.",
    partial: "A few links are vague, empty, or point to missing page sections.",
    fail: "Too many links make their destination unclear or do not resolve as expected.",
    notMeasured: "Link clarity could not be measured.",
    recommendation: "Replace vague link text with the destination or action and repair broken anchors.",
  },
  "experience.imageAlternatives": {
    title: "Image alternatives",
    pass: "Meaningful images generally include text alternatives.",
    partial: "Some images are missing useful alternative text.",
    fail: "Many images cannot be interpreted by screen readers or image search.",
    notMeasured: "Image alternatives could not be measured.",
    recommendation: "Write concise alt text for informative images and leave decorative images empty.",
  },
  "experience.controlNames": {
    title: "Form and button labels",
    pass: "Interactive controls have accessible names.",
    partial: "Some fields or buttons may be difficult to identify without visual context.",
    fail: "Important fields or buttons do not have reliable accessible names.",
    notMeasured: "No applicable controls were found in the representative pages.",
    recommendation: "Connect every field to a visible label and give icon buttons an accessible name.",
  },
  "experience.accessibilityLab": {
    title: "Mobile accessibility lab check",
    pass: "The mobile lab accessibility baseline is strong.",
    partial: "The lab check found accessibility friction worth reviewing.",
    fail: "The mobile lab check points to substantial accessibility barriers.",
    notMeasured: "PageSpeed accessibility data was unavailable for this run.",
    recommendation: "Review the Lighthouse accessibility details, then verify fixes with keyboard and screen-reader testing.",
  },
  "positioning.offerClarity": {
    title: "Offer clarity",
    pass: "The primary heading gives visitors a useful signal about the offer.",
    partial: "The main heading exists, but the offer could be more specific.",
    fail: "A new visitor may not quickly understand what the business offers.",
    notMeasured: "Offer clarity needs expert review.",
    recommendation: "Lead with a specific outcome, service, or product rather than a generic brand statement.",
  },
  "positioning.audienceRelevance": {
    title: "Audience relevance",
    pass: "The page language and stated audience create a plausible connection.",
    partial: "The business is present, but the intended audience is not consistently explicit.",
    fail: "The page does little to show the intended audience that it is for them.",
    notMeasured: "Audience relevance needs expert review.",
    recommendation: "Name the audience and the situation that brought them to the page.",
  },
  "positioning.primaryCta": {
    title: "Primary call to action",
    pass: "The visible call to action aligns with the visitor action you selected.",
    partial: "A call to action exists, but it may not match the website's most important job.",
    fail: "The page does not make the most valuable next step obvious.",
    notMeasured: "Call-to-action clarity needs expert review.",
    recommendation: "Choose one primary action, name it directly, and repeat it at decisive moments.",
  },
  "positioning.differentiation": {
    title: "Differentiation",
    pass: "You report that a new visitor can explain what makes the business different.",
    partial: "The distinction is only partly clear to a new visitor.",
    fail: "The website is not yet making the business difference memorable.",
    notMeasured: "You marked differentiation as uncertain; a short expert review is appropriate.",
    recommendation: "Replace broad claims with a clear point of view, proof, or meaningful specialty.",
  },
  "positioning.trustEvidence": {
    title: "Trust evidence",
    pass: "Representative pages include recognizable proof or credibility signals.",
    partial: "Some proof exists, but it is thin or isolated.",
    fail: "The website asks visitors to trust claims without enough visible evidence.",
    notMeasured: "Trust evidence needs expert review.",
    recommendation: "Connect important claims to case outcomes, named credentials, testimonials, or concrete examples.",
  },
  "positioning.conversionPath": {
    title: "Conversion path",
    pass: "A visitor can reach a contact, booking, or conversion path from the analyzed pages.",
    partial: "A CTA exists, but the full path to completion is not obvious in the representative crawl.",
    fail: "The analyzed pages do not expose a dependable path to conversion.",
    notMeasured: "The conversion path could not be measured.",
    recommendation: "Create one low-friction route from intent to contact, booking, purchase, or sign-up.",
  },
  "positioning.expectedResults": {
    title: "Commercial performance",
    pass: "You report that the website is producing the actions the business expects.",
    partial: "The website is producing some, but not all, of the expected actions.",
    fail: "You report that the site is not producing the expected inquiries or actions.",
    notMeasured: "You marked current website performance as uncertain.",
    recommendation: "Define the primary conversion, verify tracking, and diagnose the largest drop-off first.",
  },
  "search.indexability": {
    title: "Indexability",
    pass: "The submitted page does not declare a noindex directive.",
    partial: "Indexability has a condition that deserves review.",
    fail: "The submitted page asks search engines not to index it.",
    notMeasured: "Indexability could not be verified.",
    recommendation: "Remove unintended noindex directives before doing other search optimization.",
  },
  "search.title": {
    title: "Page title",
    pass: "The submitted page has a useful title within a practical length range.",
    partial: "A title exists, but its length or specificity may limit its usefulness.",
    fail: "The submitted page is missing a usable title.",
    notMeasured: "The page title could not be measured.",
    recommendation: "Write a unique title that pairs the page topic with the brand in roughly 20–65 characters.",
  },
  "search.description": {
    title: "Meta description",
    pass: "The description gives search visitors a useful summary of the page.",
    partial: "A description exists, but it is unusually short or long.",
    fail: "The submitted page has no meta description.",
    notMeasured: "The meta description could not be measured.",
    recommendation: "Write a specific, benefit-led summary that earns the click without repeating the title.",
  },
  "search.canonical": {
    title: "Canonical URL",
    pass: "The submitted page identifies its preferred canonical URL.",
    partial: "The canonical signal needs review.",
    fail: "The submitted page does not expose a canonical URL.",
    notMeasured: "The canonical URL could not be measured.",
    recommendation: "Add a self-referencing canonical to the page template and validate alternate URL variants.",
  },
  "search.primaryHeading": {
    title: "Primary heading",
    pass: "The submitted page uses one clear H1.",
    partial: "The page has multiple primary headings.",
    fail: "The page does not expose a primary heading.",
    notMeasured: "The primary heading could not be measured.",
    recommendation: "Use one visible, descriptive H1 that matches the page's real topic.",
  },
  "search.internalLinks": {
    title: "Internal links",
    pass: "The submitted page offers several paths to related site content.",
    partial: "The page links internally, but the path network is thin.",
    fail: "The submitted page exposes very few useful internal links.",
    notMeasured: "Internal linking could not be measured.",
    recommendation: "Link the page to the next most useful service, proof, and conversion pages.",
  },
  "search.imageText": {
    title: "Image text alternatives for search",
    pass: "Most meaningful images carry useful text alternatives.",
    partial: "Image descriptions are inconsistent.",
    fail: "A substantial share of images lack text alternatives.",
    notMeasured: "Image alternatives could not be measured.",
    recommendation: "Describe informative images with concise, contextual alt text.",
  },
  "search.structuredData": {
    title: "Structured data",
    pass: "At least one valid JSON-LD block was detected.",
    partial: "Structured data is present but incomplete or unsupported.",
    fail: "No valid JSON-LD was detected in the representative pages.",
    notMeasured: "Structured data could not be measured.",
    recommendation: "Add accurate schema for the organization and the page's real content type.",
  },
  "search.pageDiscovery": {
    title: "Representative page discovery",
    pass: "Navigation exposed a useful set of representative pages.",
    partial: "Only part of the expected site structure was discoverable from navigation.",
    fail: "The submitted page exposed little additional same-domain content.",
    notMeasured: "Representative page discovery could not run.",
    recommendation: "Make core services, proof, about, and contact paths discoverable through plain internal links.",
  },
  "search.seoLab": {
    title: "Mobile Lighthouse search baseline",
    pass: "The mobile Lighthouse SEO baseline is strong.",
    partial: "The mobile Lighthouse SEO baseline has issues worth reviewing.",
    fail: "The mobile Lighthouse SEO baseline found major discoverability problems.",
    notMeasured: "The Lighthouse SEO category was unavailable; it did not reduce the score.",
    recommendation: "Review the failed Lighthouse SEO audits alongside the page-level findings before prioritizing changes.",
  },
  "ai.entityLanguage": {
    title: "Business and entity clarity",
    pass: "The content consistently provides cues about who the organization is.",
    partial: "Entity cues are present but inconsistent across the representative pages.",
    fail: "The content provides few explicit cues about the organization behind it.",
    notMeasured: "Entity clarity needs expert review.",
    recommendation: "State the organization name, role, market, and location consistently in visible copy.",
  },
  "ai.serviceLanguage": {
    title: "Service and product language",
    pass: "The content explicitly names what the organization provides.",
    partial: "Some pages name the offer clearly while others rely on generic language.",
    fail: "Services or products are difficult to identify from the visible content.",
    notMeasured: "Service language needs expert review.",
    recommendation: "Use the words customers use for the actual services, products, and outcomes.",
  },
  "ai.answerStructure": {
    title: "Answerable content structure",
    pass: "Several sections pair descriptive headings with self-contained explanations.",
    partial: "At least one section is structured as a useful, direct answer.",
    fail: "Important information is not organized into easily answerable sections.",
    notMeasured: "Answer structure needs expert review.",
    recommendation: "Turn key customer questions into descriptive headings followed by direct, complete answers.",
  },
  "ai.evidenceAuthorship": {
    title: "Evidence and authorship",
    pass: "Representative content includes authorship or concrete trust evidence.",
    partial: "Evidence exists, but it is not consistently connected to key claims.",
    fail: "Claims rarely show who is responsible or what evidence supports them.",
    notMeasured: "Evidence and authorship need expert review.",
    recommendation: "Add named authorship where relevant and attach proof to consequential claims.",
  },
  "ai.machineReadableOrganization": {
    title: "Machine-readable organization",
    pass: "Structured data describes the organization or its services.",
    partial: "JSON-LD exists but does not clearly represent the organization or offer.",
    fail: "No machine-readable organization or service relationship was detected.",
    notMeasured: "Machine-readable organization data could not be measured.",
    recommendation: "Use accurate Organization, LocalBusiness, Product, or Service schema where applicable.",
  },
  "ai.crawlableContent": {
    title: "Crawlable explanatory content",
    pass: "The submitted page exposes a useful amount of indexable explanatory copy.",
    partial: "Some crawlable copy exists, but important context may be thin.",
    fail: "The submitted page exposes little crawlable explanatory content.",
    notMeasured: "Crawlable content could not be measured.",
    recommendation: "Put essential business and offer context in the initial HTML, not only behind interaction.",
  },
  "technical.https": {
    title: "Secure delivery",
    pass: "The final page is delivered over HTTPS.",
    partial: "Secure delivery needs review.",
    fail: "The final page is not delivered over HTTPS.",
    notMeasured: "Secure delivery could not be verified.",
    recommendation: "Redirect all public traffic to a valid HTTPS origin.",
  },
  "technical.responseHealth": {
    title: "Response health",
    pass: "All representative pages returned successful responses.",
    partial: "At least one representative page returned an unhealthy response.",
    fail: "Several representative pages did not return healthy responses.",
    notMeasured: "Response health could not be measured.",
    recommendation: "Repair broken destinations and redirect retired URLs to the closest useful page.",
  },
  "technical.rendering": {
    title: "HTML rendering health",
    pass: "Representative pages returned usable HTML and visible content.",
    partial: "Some pages returned very little visible HTML content.",
    fail: "The crawl could not consistently retrieve usable rendered content.",
    notMeasured: "Rendering health could not be measured.",
    recommendation: "Ensure essential content is available in the initial HTML response and investigate failed templates.",
  },
  "technical.mobilePerformance": {
    title: "Mobile performance",
    pass: "The mobile PageSpeed performance baseline is strong.",
    partial: "Mobile performance is usable but leaves meaningful room to improve.",
    fail: "The mobile lab result points to serious performance friction.",
    notMeasured: "PageSpeed performance data was unavailable; it did not reduce the score.",
    recommendation: "Start with the largest image, font, and main-thread costs identified by PageSpeed.",
  },
  "technical.coreWebVitals": {
    title: "Lab loading and stability",
    pass: "Lab LCP and layout stability are within strong thresholds.",
    partial: "Loading or layout stability needs improvement.",
    fail: "The lab check found slow loading or disruptive layout movement.",
    notMeasured: "Lab LCP and CLS data were unavailable; they did not reduce the score.",
    recommendation: "Prioritize the largest content element and reserve space for late-loading media and embeds.",
  },
  "technical.bestPracticesLab": {
    title: "Mobile technical best practices",
    pass: "The mobile Lighthouse best-practices baseline is strong.",
    partial: "The mobile best-practices baseline has technical risks to review.",
    fail: "The mobile best-practices baseline found significant technical risks.",
    notMeasured: "The Lighthouse best-practices category was unavailable; it did not reduce the score.",
    recommendation: "Review browser errors, insecure resources, and deprecated behavior flagged by Lighthouse.",
  },
};

export const enAuditCopy: AuditCopy = {
  meta: {
    title: "Website Opportunity Audit | LV Branding",
    description: "See where your website supports clarity, trust, discovery and action, and what deserves attention first.",
    productName: "LV Website Opportunity Audit",
    shortName: "Website Opportunity Audit",
    mobileName: "Website Audit",
    descriptor: "A free clarity, experience and discoverability audit by LV Branding",
  },
  common: {
    language: "Language",
    english: "English",
    spanish: "Español",
    back: "Back",
    continue: "Continue",
    startOver: "Start over",
    cancel: "Cancel",
    optional: "optional",
    website: "Website",
    close: "Close",
    yes: "Yes",
    no: "No",
  },
  landing: {
    eyebrow: "Free website clarity audit",
    heading: "Your website is always saying something.",
    emphasis: "Make sure it is saying the right thing.",
    body: "See where your website is helping the business, where it is creating friction, and what deserves attention first.",
    urlLabel: "Enter a public website address",
    urlPlaceholder: "yourwebsite.com",
    cta: "Audit My Website",
    workingCta: "Checking address…",
    reassurance: "No account · no email gate · about 2 minutes",
    acceptTerms: "I confirm I may submit this public website for an automated audit.",
    termsRequired: "Confirm permission to audit this public website before continuing.",
    termsLead: "Review the",
    terms: "audit terms",
    termsBody: "Only submit a public website you are permitted to review. The audit makes a limited, automated request to public pages, stores normalized signals for up to 30 days, and is provided for planning, not as a certification, legal opinion, accessibility conformance claim, or guarantee of search or AI placement.",
    privacy: "We review public pages only. URLs and opted-in contact details follow LV Branding's privacy practices.",
    sampleLead: "Want to see the report before running an audit?",
    sampleCta: "Explore a sample result",
    representative: "Focused, not overwhelming",
    representativeBody: "We review the submitted page and up to four useful same-domain pages, not an endless crawl.",
    evidence: "Evidence you can trust",
    evidenceBody: "Every finding says whether it was verified, inferred, self-reported, or needs an expert review.",
    useful: "A plan, not a pile of errors",
    usefulBody: "Your result leads with the three opportunities most likely to improve clarity, discovery, or action.",
    dimensionEyebrow: "One website. Five business lenses.",
    dimensionHeading: "More useful than a generic SEO score.",
    dimensionBody: "The Website Opportunity Score combines observable site signals with transparent evaluation rules. It is a planning tool, not a certification or a promise of search or AI placement.",
    stepsHeading: "What happens after you enter your website",
    steps: [
      { number: "01", title: "Add business context", body: "Tell us what the site needs to accomplish and who it needs to reach." },
      { number: "02", title: "We review public signals", body: "The audit examines representative pages, mobile signals, structure, content, and discoverability." },
      { number: "03", title: "Get a prioritized plan", body: "See five dimension scores, clear evidence, and the three actions worth addressing first." },
    ],
    badges: ["Public pages only", "Result without email", "English + Español"],
  },
  context: {
    progress: "A little context makes the result more useful",
    heading: "What does this website need to do for the business?",
    body: "Automation can read a page. It cannot know the strategy behind it. These answers calibrate positioning and conversion findings without replacing observed evidence.",
    businessType: "What kind of business or organization is this?",
    audience: "Who must understand the offer first?",
    audienceHint: "A short, specific answer works best.",
    audiencePlaceholder: "For example: operations leaders at growing manufacturers",
    purpose: "What is the website's primary job?",
    conversionAction: "What is the single most important visitor action?",
    differentiation: "Can a new visitor explain what makes the business different after viewing the homepage?",
    differentiationHint: "Your honest answer helps us separate content friction from technical issues.",
    expectedResults: "Is the site producing the inquiries or actions the business expects?",
    expectedResultsHint: "This is self-reported context, not a technical finding.",
    lastReviewed: "When was the site's structure or content last deliberately reviewed?",
    required: "Complete this question.",
    submit: "Start the Audit",
    businessTypes: [
      { value: "professional-services", label: "Professional services" },
      { value: "local-business", label: "Local business" },
      { value: "b2b", label: "B2B company" },
      { value: "ecommerce", label: "Ecommerce" },
      { value: "nonprofit", label: "Nonprofit" },
      { value: "platform", label: "Platform or portal" },
      { value: "other", label: "Something else" },
    ],
    purposes: [
      { value: "generate-leads", label: "Generate leads", hint: "Create qualified conversations" },
      { value: "sell", label: "Sell", hint: "Drive purchases or subscriptions" },
      { value: "book", label: "Book", hint: "Schedule services or appointments" },
      { value: "educate", label: "Educate", hint: "Explain an issue, offer, or point of view" },
      { value: "partners", label: "Attract partners", hint: "Build credibility with collaborators or funders" },
      { value: "support", label: "Support customers", hint: "Help existing customers complete a task" },
    ],
    conversionActions: [
      { value: "contact", label: "Contact the team" },
      { value: "request-quote", label: "Request a quote" },
      { value: "book", label: "Book or schedule" },
      { value: "buy", label: "Buy" },
      { value: "sign-up", label: "Sign up" },
      { value: "use-tool", label: "Use a tool or portal" },
      { value: "call", label: "Call" },
      { value: "other", label: "Another action" },
    ],
    ternary: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
      { value: "unsure", label: "Not sure" },
    ],
    reviewRecency: [
      { value: "six-months", label: "Within 6 months" },
      { value: "one-year", label: "6–12 months ago" },
      { value: "two-years", label: "1–2+ years ago" },
      { value: "unknown", label: "Not sure" },
    ],
  },
  analyzing: {
    eyebrow: "Audit in progress",
    heading: "We are reading the website the way a customer might.",
    body: "This can take a little while. Keep this tab open; there is no need to refresh.",
    stages: ["Connecting securely", "Reviewing representative pages", "Checking mobile and technical signals", "Building your opportunity plan"],
    patience: "Most audits finish within a minute. Some websites or PageSpeed checks take longer.",
    failedHeading: "We could not complete this audit.",
    failedBody: "The site may block automated reviews, return unsupported content, or the audit service may not be deployed yet.",
    tryAgain: "Try again",
    sampleInstead: "View a sample result",
  },
  results: {
    sampleBanner: "Sample report",
    sampleBannerBody: "This is representative demo data for a fictional website. No live website was fetched.",
    eyebrow: "Your website opportunity report",
    reportFor: "Report for",
    auditedOn: "Audited",
    pagesAnalyzed: (count) => `${count} representative page${count === 1 ? "" : "s"} analyzed`,
    pageLanguage: "Detected page language",
    pagePreview: "Submitted page preview",
    pagePreviewNote: "Built from the title and heading found in the page, not a visual screenshot.",
    pageScreenshotNote: "Mobile page capture supplied by Lighthouse at audit time.",
    pageScreenshotAlt: "Mobile screenshot of the submitted website",
    englishPage: "English",
    spanishPage: "Spanish",
    unknownPage: "Not confirmed",
    opportunityScore: "Website Opportunity Score",
    outOf: "out of 100",
    coverage: "Evidence coverage",
    coverageShort: "measured",
    coverageBody: "Unavailable checks are removed from scoring, so missing data lowers coverage rather than your score.",
    diagnosis: {
      strong: "A strong foundation with specific opportunities to protect and optimize.",
      friction: "The site is working, but avoidable friction may be costing clarity, visibility, or action.",
      constrained: "Several issues are likely constraining trust, discovery, or conversion.",
      rebuild: "Structural problems may cost more to patch than to rethink as a connected experience.",
    },
    dimensionHeading: "Five views of the same customer experience",
    dimensionBody: "Each score uses only applicable, measured checks. Open the full findings to see exactly what moved each number.",
    working: "What is working",
    friction: "What creates friction",
    noStrength: "No measured check reached a full pass in this dimension yet.",
    noFriction: "No measured check created scored friction in this dimension.",
    nextAction: "Recommended action",
    protectDimension: "Keep the strongest measured pattern intact and review it whenever this experience changes.",
    priorityEyebrow: "Your opportunity plan",
    priorityHeading: "Start with the moves that matter most.",
    priorityBody: "Priority is ranked separately from score using severity, business impact, confidence, and effort.",
    priorityHeadingClear: "Protect the foundation you already have.",
    priorityBodyClear: "No measured check created a repair action. Keep the strongest pattern intact and review any missing evidence separately.",
    fixNow: "Fix now",
    fixNowHint: "High impact · low or moderate effort",
    planNext: "Plan next",
    planNextHint: "A larger opportunity that needs coordination",
    protect: "Protect",
    protectHint: "A strength worth carrying through future changes",
    fullFindings: "View all findings",
    fullFindingsBody: "See every measured check, its evidence type, and the rule behind it.",
    findingsCount: (count) => `${count} finding${count === 1 ? "" : "s"}`,
    notMeasured: "Not measured",
    pageScope: "Audit scope and coverage",
    analyzed: "Analyzed pages",
    labUnavailable: "PageSpeed data was not available for this run. Performance checks were excluded from the denominator.",
    pageScopeIncomplete: "One or more representative pages could not be retrieved. Those gaps reduced coverage instead of lowering the score.",
    aiDisclaimer: "AI Answer Readiness evaluates content accessibility and clarity. It does not predict or guarantee placement in any AI product.",
    runAnother: "Audit another website",
    sampleCtaHeading: "Now make the report yours.",
    sampleCtaBody: "Run the same transparent review on your public website. Your complete result is available without an account or email address.",
    sampleCtaAction: "Audit My Website",
  },
  dimensions: {
    experience: { label: "Experience & Usability", short: "Experience", description: "How easily people can navigate, scan, understand, and interact on mobile." },
    positioning: { label: "Positioning & Conversion", short: "Positioning", description: "How clearly the site communicates relevance, difference, proof, and the next step." },
    search: { label: "Search Discoverability", short: "Search", description: "Whether search engines can interpret, index, and connect the site's key content." },
    aiReadiness: { label: "AI Answer Readiness", short: "AI readiness", description: "Whether content is explicit, structured, supported, and easy for answer systems to interpret." },
    technical: { label: "Technical Health", short: "Technical", description: "Response, rendering, security, mobile performance, and stability signals." },
  },
  bands: {
    strong: { label: "Strong foundation", meaning: "Protect what works and optimize specific opportunities" },
    friction: { label: "Working, with friction", meaning: "Functional, but likely losing some clarity, visibility, or conversions" },
    constrained: { label: "Growth constrained", meaning: "Several issues are likely limiting trust, discovery, or action" },
    rebuild: { label: "Rebuild territory", meaning: "Structural problems may cost more to patch than to rethink" },
  },
  evidence: {
    verified: { label: "Verified", description: "Observed directly in the page, response, or audit data." },
    inferred: { label: "Inferred", description: "Determined through a transparent content or interface rule." },
    selfReported: { label: "Self-reported", description: "Based on the context you provided." },
    needsReview: { label: "Needs expert review", description: "Cannot be judged responsibly by automation alone." },
  },
  outcomes: { pass: "Working", partial: "Opportunity", fail: "Needs attention", notMeasured: "Not measured" },
  rules,
  routes: {
    improve: { label: "Improve This Website", heading: "This site is worth improving with precision.", body: "The foundation is viable. Focus on the highest-value gaps without disturbing what already works.", action: "Improve This Website" },
    ux: { label: "Plan a UX/UI Improvement", heading: "The structure can work harder for visitors.", body: "A focused UX/UI improvement can remove friction while preserving the viable parts of the current site.", action: "Plan a UX/UI Improvement" },
    redesign: { label: "Explore a Website Redesign", heading: "The issues are connected, not isolated.", body: "Positioning, experience, and technical constraints point to a coordinated redesign rather than a string of patches.", action: "Explore a Website Redesign" },
    platform: { label: "Discuss a Custom Web Platform", heading: "The website may need to do more than publish pages.", body: "A workflow, portal, or interactive task may call for a custom platform approach alongside the public experience.", action: "Discuss a Custom Web Platform" },
  },
  lead: {
    supporting: "Your audit found where the friction is. LV Branding can help you decide what to repair, what to redesign, and what is not worth touching.",
    openForm: "Ask LV Branding for help",
    heading: "Tell us where you want to go next.",
    body: "Your website and audit context are already attached. We only need enough information to route the conversation well.",
    name: "Name",
    email: "Work email",
    company: "Company",
    pathway: "Preferred help pathway",
    timeline: "Timeline",
    context: "Project context",
    contextPlaceholder: "Anything important about the site, team, or next decision?",
    consent: "I agree that LV Branding may use this audit and my contact details to respond to this request.",
    disclosure: "We send the audit URL, scores, top opportunities, preferred pathway, timeline, and the details entered here.",
    submit: "Send My Request",
    submitting: "Sending…",
    successHeading: "Your audit is with the right team.",
    successBody: "We will review the context and follow up within one business day. Your result stays available in this browser.",
    error: "We could not send the request. Please try again or email luis@lvbranding.com.",
    required: "Complete this field.",
    invalidEmail: "Enter a valid work email.",
    timelines: [
      { value: "now", label: "Now" },
      { value: "one-three", label: "1–3 months" },
      { value: "three-six", label: "3–6 months" },
      { value: "exploring", label: "Exploring" },
    ],
  },
  errors: {
    urlRequired: "Enter a website address to continue.",
    urlInvalid: "Enter a valid website address, such as example.com.",
    urlPublicOnly: "Use a public http or https website, not localhost or a private network address.",
    contextRequired: "Complete the required context so the audit can interpret the site responsibly.",
    auditUnavailable: "The live audit service is unavailable right now.",
    rateLimited: "This website or connection has reached the audit limit. Please try again later.",
    siteUnreachable: "We could not reach or resolve this website. Confirm the address and that the site is publicly available.",
    siteTimeout: "The website took too long to respond. Try again when it is responding normally.",
    unsupportedContent: "That address did not return a public HTML page we can audit.",
    unhealthyResponse: "The submitted page returned an unsuccessful response and could not be audited.",
    responseTooLarge: "The submitted page is larger than this representative audit can safely process.",
    redirectFailed: "The website's redirect path could not be followed safely.",
    resultMissing: "This result is not available in this browser. Run a new audit to continue.",
    resultExpired: "This private result link is invalid or has expired.",
    resultVersionUnsupported: "This result uses an older audit version and cannot be safely recalculated. Run a new audit for a current report.",
    resultUnavailable: "We could not load this result right now. Your private link may still be valid.",
    retryResult: "Try loading again",
  },
  footer: "Made with love by LV Branding",
};
