import type { AuditCopy } from "./types.ts";

const rules: AuditCopy["rules"] = {
  "experience.mobileViewport": {
    title: "Vista móvil",
    pass: "Las páginas analizadas indican a los navegadores móviles cómo adaptar la experiencia.",
    partial: "Algunas páginas no incluyen una configuración confiable para la vista móvil.",
    fail: "La experiencia enviada no declara una vista móvil.",
    notMeasured: "No fue posible medir las señales de vista móvil.",
    recommendation: "Agrega una declaración de viewport responsivo a todas las plantillas de página.",
  },
  "experience.headingStructure": {
    title: "Estructura de encabezados",
    pass: "Los encabezados crean una jerarquía clara y fácil de recorrer.",
    partial: "La jerarquía ayuda en algunas secciones, pero no es consistente.",
    fail: "Puede ser difícil comprender la jerarquía de la página, especialmente con tecnología de asistencia.",
    notMeasured: "No fue posible medir la estructura de encabezados.",
    recommendation: "Usa un H1 descriptivo por página y organiza las secciones en un orden lógico.",
  },
  "experience.linkClarity": {
    title: "Claridad de enlaces",
    pass: "La mayoría de los enlaces explica su destino y los anclajes internos funcionan.",
    partial: "Algunos enlaces son vagos, están vacíos o apuntan a secciones inexistentes.",
    fail: "Demasiados enlaces ocultan su destino o no funcionan como se espera.",
    notMeasured: "No fue posible medir la claridad de los enlaces.",
    recommendation: "Nombra el destino o la acción en cada enlace y corrige los anclajes rotos.",
  },
  "experience.imageAlternatives": {
    title: "Alternativas para imágenes",
    pass: "Las imágenes informativas suelen incluir texto alternativo.",
    partial: "Algunas imágenes no tienen una alternativa de texto útil.",
    fail: "Muchas imágenes no se pueden interpretar con lectores de pantalla ni búsqueda visual.",
    notMeasured: "No fue posible medir las alternativas para imágenes.",
    recommendation: "Describe las imágenes informativas de forma breve y deja vacías las decorativas.",
  },
  "experience.controlNames": {
    title: "Etiquetas de formularios y botones",
    pass: "Los controles interactivos tienen nombres accesibles.",
    partial: "Algunos campos o botones dependen demasiado del contexto visual.",
    fail: "Hay campos o botones importantes sin un nombre accesible confiable.",
    notMeasured: "No se encontraron controles aplicables en las páginas representativas.",
    recommendation: "Vincula cada campo con una etiqueta visible y nombra los botones que solo usan íconos.",
  },
  "experience.accessibilityLab": {
    title: "Prueba móvil de accesibilidad",
    pass: "La base móvil de accesibilidad es sólida.",
    partial: "La prueba detectó fricción de accesibilidad que conviene revisar.",
    fail: "La prueba móvil señala barreras de accesibilidad importantes.",
    notMeasured: "Los datos de accesibilidad de PageSpeed no estuvieron disponibles.",
    recommendation: "Revisa los detalles de Lighthouse y valida los cambios con teclado y lector de pantalla.",
  },
  "positioning.offerClarity": {
    title: "Claridad de la oferta",
    pass: "El encabezado principal da una señal útil sobre la oferta.",
    partial: "El encabezado existe, pero la oferta podría ser más específica.",
    fail: "Una persona nueva podría no entender rápidamente qué ofrece el negocio.",
    notMeasured: "La claridad de la oferta requiere revisión experta.",
    recommendation: "Abre con un resultado, servicio o producto concreto, no con una frase genérica de marca.",
  },
  "positioning.audienceRelevance": {
    title: "Relevancia para la audiencia",
    pass: "El lenguaje de la página conecta de forma plausible con la audiencia indicada.",
    partial: "El negocio se entiende, pero la audiencia no aparece con consistencia.",
    fail: "La página ofrece pocas señales de que fue creada para la audiencia prioritaria.",
    notMeasured: "La relevancia para la audiencia requiere revisión experta.",
    recommendation: "Nombra a la audiencia y la situación que la llevó a visitar la página.",
  },
  "positioning.primaryCta": {
    title: "Llamado a la acción principal",
    pass: "El llamado visible coincide con la acción que seleccionaste.",
    partial: "Hay un llamado a la acción, pero puede no corresponder con el objetivo principal del sitio.",
    fail: "La página no deja claro cuál es el siguiente paso más valioso.",
    notMeasured: "La claridad del llamado a la acción requiere revisión experta.",
    recommendation: "Elige una acción principal, nómbrala directamente y repítela en momentos decisivos.",
  },
  "positioning.differentiation": {
    title: "Diferenciación",
    pass: "Indicas que una persona nueva puede explicar qué hace diferente al negocio.",
    partial: "La diferencia solo se entiende parcialmente.",
    fail: "El sitio aún no convierte la diferencia del negocio en algo memorable.",
    notMeasured: "Marcaste la diferenciación como incierta; conviene una revisión experta breve.",
    recommendation: "Sustituye afirmaciones amplias por un punto de vista, prueba o especialidad concreta.",
  },
  "positioning.trustEvidence": {
    title: "Evidencia de confianza",
    pass: "Las páginas representativas incluyen pruebas o señales de credibilidad reconocibles.",
    partial: "Existe algo de evidencia, pero es limitada o está aislada.",
    fail: "El sitio pide confiar en sus afirmaciones sin mostrar suficiente evidencia.",
    notMeasured: "La evidencia de confianza requiere revisión experta.",
    recommendation: "Relaciona las afirmaciones clave con resultados, credenciales, testimonios o ejemplos concretos.",
  },
  "positioning.conversionPath": {
    title: "Ruta de conversión",
    pass: "Es posible llegar a una ruta de contacto, reserva o conversión desde las páginas analizadas.",
    partial: "Hay un llamado, pero el camino completo no es evidente en la muestra.",
    fail: "Las páginas analizadas no muestran una ruta confiable hacia la conversión.",
    notMeasured: "No fue posible medir la ruta de conversión.",
    recommendation: "Crea un camino simple desde la intención hasta el contacto, reserva, compra o registro.",
  },
  "positioning.expectedResults": {
    title: "Rendimiento comercial",
    pass: "Indicas que el sitio produce las acciones que el negocio espera.",
    partial: "El sitio produce algunas de las acciones esperadas, pero no todas.",
    fail: "Indicas que el sitio no está generando las consultas o acciones esperadas.",
    notMeasured: "Marcaste el rendimiento actual como incierto.",
    recommendation: "Define la conversión principal, verifica su medición y analiza primero la mayor fuga.",
  },
  "search.indexability": {
    title: "Indexabilidad",
    pass: "La página enviada no declara una instrucción noindex.",
    partial: "Hay una condición de indexación que conviene revisar.",
    fail: "La página enviada pide a los buscadores que no la indexen.",
    notMeasured: "No fue posible verificar la indexabilidad.",
    recommendation: "Elimina instrucciones noindex involuntarias antes de optimizar otros aspectos.",
  },
  "search.title": {
    title: "Título de página",
    pass: "La página tiene un título útil dentro de un rango práctico.",
    partial: "Existe un título, pero su longitud o precisión puede limitarlo.",
    fail: "La página no tiene un título útil.",
    notMeasured: "No fue posible medir el título.",
    recommendation: "Escribe un título único de 20–65 caracteres que una el tema de la página con la marca.",
  },
  "search.description": {
    title: "Metadescripción",
    pass: "La descripción ofrece un resumen útil para quien llega desde búsqueda.",
    partial: "Existe una descripción, pero es demasiado corta o extensa.",
    fail: "La página enviada no tiene metadescripción.",
    notMeasured: "No fue posible medir la metadescripción.",
    recommendation: "Resume el beneficio de la página con precisión sin repetir el título.",
  },
  "search.canonical": {
    title: "URL canónica",
    pass: "La página identifica su URL canónica preferida.",
    partial: "La señal canónica necesita revisión.",
    fail: "La página no expone una URL canónica.",
    notMeasured: "No fue posible medir la URL canónica.",
    recommendation: "Agrega una canónica autorreferente a la plantilla y valida las variantes de URL.",
  },
  "search.primaryHeading": {
    title: "Encabezado principal",
    pass: "La página enviada usa un solo H1 claro.",
    partial: "La página usa varios encabezados principales.",
    fail: "La página no expone un encabezado principal.",
    notMeasured: "No fue posible medir el encabezado principal.",
    recommendation: "Usa un H1 visible y descriptivo que represente el tema real de la página.",
  },
  "search.internalLinks": {
    title: "Enlaces internos",
    pass: "La página ofrece varios caminos hacia contenido relacionado.",
    partial: "Hay enlaces internos, pero la red de caminos es limitada.",
    fail: "La página expone muy pocos enlaces internos útiles.",
    notMeasured: "No fue posible medir los enlaces internos.",
    recommendation: "Enlaza al siguiente servicio, prueba y página de conversión más útiles.",
  },
  "search.imageText": {
    title: "Texto de imágenes para búsqueda",
    pass: "La mayoría de las imágenes informativas tiene texto alternativo útil.",
    partial: "Las descripciones de imágenes son inconsistentes.",
    fail: "Una proporción importante de imágenes no tiene alternativa de texto.",
    notMeasured: "No fue posible medir las alternativas para imágenes.",
    recommendation: "Describe las imágenes informativas con texto alternativo breve y contextual.",
  },
  "search.structuredData": {
    title: "Datos estructurados",
    pass: "Se detectó al menos un bloque JSON-LD válido.",
    partial: "Hay datos estructurados, pero son incompletos o no compatibles.",
    fail: "No se detectó JSON-LD válido en las páginas representativas.",
    notMeasured: "No fue posible medir los datos estructurados.",
    recommendation: "Agrega schema preciso para la organización y el tipo real de contenido.",
  },
  "search.pageDiscovery": {
    title: "Descubrimiento de páginas",
    pass: "La navegación expuso un conjunto útil de páginas representativas.",
    partial: "Solo parte de la estructura esperada fue visible desde la navegación.",
    fail: "La página enviada expuso poco contenido adicional del mismo dominio.",
    notMeasured: "No fue posible descubrir páginas representativas.",
    recommendation: "Haz visibles los servicios, pruebas, información y contacto con enlaces internos simples.",
  },
  "search.seoLab": {
    title: "Base móvil de búsqueda en Lighthouse",
    pass: "La base SEO móvil de Lighthouse es sólida.",
    partial: "La base SEO móvil de Lighthouse tiene aspectos que conviene revisar.",
    fail: "La base SEO móvil de Lighthouse detectó problemas importantes de visibilidad.",
    notMeasured: "La categoría SEO de Lighthouse no estuvo disponible y no redujo el índice.",
    recommendation: "Revisa las pruebas SEO fallidas de Lighthouse junto con los hallazgos de la página antes de priorizar cambios.",
  },
  "ai.entityLanguage": {
    title: "Claridad de negocio y entidad",
    pass: "El contenido ofrece señales consistentes sobre quién es la organización.",
    partial: "Hay señales de entidad, pero varían entre páginas.",
    fail: "El contenido ofrece pocas señales explícitas sobre la organización responsable.",
    notMeasured: "La claridad de entidad requiere revisión experta.",
    recommendation: "Menciona de forma consistente el nombre, función, mercado y ubicación de la organización.",
  },
  "ai.serviceLanguage": {
    title: "Lenguaje de servicios y productos",
    pass: "El contenido nombra explícitamente lo que ofrece la organización.",
    partial: "Algunas páginas son claras y otras dependen de lenguaje genérico.",
    fail: "Los servicios o productos son difíciles de identificar en el contenido visible.",
    notMeasured: "El lenguaje de servicios requiere revisión experta.",
    recommendation: "Usa las palabras que los clientes emplean para los servicios, productos y resultados reales.",
  },
  "ai.answerStructure": {
    title: "Estructura fácil de responder",
    pass: "Varias secciones combinan encabezados descriptivos con explicaciones completas.",
    partial: "Al menos una sección funciona como una respuesta directa y útil.",
    fail: "La información importante no está organizada en secciones fáciles de interpretar.",
    notMeasured: "La estructura de respuestas requiere revisión experta.",
    recommendation: "Convierte preguntas clave en encabezados descriptivos seguidos de respuestas completas.",
  },
  "ai.evidenceAuthorship": {
    title: "Evidencia y autoría",
    pass: "El contenido representativo incluye autoría o pruebas concretas.",
    partial: "Existe evidencia, pero no siempre acompaña las afirmaciones clave.",
    fail: "Las afirmaciones rara vez muestran responsable o evidencia de respaldo.",
    notMeasured: "La evidencia y autoría requieren revisión experta.",
    recommendation: "Agrega autoría cuando corresponda y conecta las afirmaciones importantes con pruebas.",
  },
  "ai.machineReadableOrganization": {
    title: "Organización legible por máquinas",
    pass: "Los datos estructurados describen la organización o sus servicios.",
    partial: "Existe JSON-LD, pero no representa con claridad a la organización o su oferta.",
    fail: "No se detectó una relación legible entre organización y servicios.",
    notMeasured: "No fue posible medir los datos de la organización.",
    recommendation: "Usa schema Organization, LocalBusiness, Product o Service cuando corresponda.",
  },
  "ai.crawlableContent": {
    title: "Contenido explicativo rastreable",
    pass: "La página expone una cantidad útil de contenido explicativo indexable.",
    partial: "Existe contenido rastreable, pero el contexto importante es limitado.",
    fail: "La página expone poco contenido explicativo rastreable.",
    notMeasured: "No fue posible medir el contenido rastreable.",
    recommendation: "Incluye el contexto esencial en el HTML inicial, no solo detrás de interacciones.",
  },
  "technical.https": {
    title: "Entrega segura",
    pass: "La página final se entrega por HTTPS.",
    partial: "La entrega segura necesita revisión.",
    fail: "La página final no se entrega por HTTPS.",
    notMeasured: "No fue posible verificar la entrega segura.",
    recommendation: "Redirige todo el tráfico público a un origen HTTPS válido.",
  },
  "technical.responseHealth": {
    title: "Estado de respuesta",
    pass: "Todas las páginas representativas respondieron correctamente.",
    partial: "Al menos una página devolvió una respuesta problemática.",
    fail: "Varias páginas representativas no devolvieron respuestas saludables.",
    notMeasured: "No fue posible medir el estado de respuesta.",
    recommendation: "Corrige destinos rotos y redirige URLs retiradas a la página útil más cercana.",
  },
  "technical.rendering": {
    title: "Salud del HTML",
    pass: "Las páginas devolvieron HTML útil y contenido visible.",
    partial: "Algunas páginas devolvieron muy poco contenido visible en HTML.",
    fail: "El rastreo no pudo obtener contenido útil de forma consistente.",
    notMeasured: "No fue posible medir la salud del HTML.",
    recommendation: "Asegura que el contenido esencial exista en la respuesta HTML inicial.",
  },
  "technical.mobilePerformance": {
    title: "Rendimiento móvil",
    pass: "La base móvil de rendimiento en PageSpeed es sólida.",
    partial: "El rendimiento móvil funciona, pero tiene oportunidades importantes.",
    fail: "La prueba móvil señala fricción grave de rendimiento.",
    notMeasured: "No hubo datos de PageSpeed; esta ausencia no redujo el índice.",
    recommendation: "Empieza con las imágenes, fuentes y tareas principales que PageSpeed señale como más costosas.",
  },
  "technical.coreWebVitals": {
    title: "Carga y estabilidad de laboratorio",
    pass: "El LCP y la estabilidad visual de laboratorio están en rangos sólidos.",
    partial: "La carga o la estabilidad visual necesita mejoras.",
    fail: "La prueba detectó carga lenta o movimientos visuales molestos.",
    notMeasured: "No hubo datos de LCP y CLS; esta ausencia no redujo el índice.",
    recommendation: "Optimiza el elemento de contenido principal y reserva espacio para medios y componentes tardíos.",
  },
  "technical.bestPracticesLab": {
    title: "Buenas prácticas técnicas móviles",
    pass: "La base móvil de buenas prácticas de Lighthouse es sólida.",
    partial: "La base móvil de buenas prácticas tiene riesgos técnicos que conviene revisar.",
    fail: "La base móvil de buenas prácticas detectó riesgos técnicos importantes.",
    notMeasured: "La categoría de buenas prácticas de Lighthouse no estuvo disponible y no redujo el índice.",
    recommendation: "Revisa errores del navegador, recursos inseguros y comportamientos obsoletos señalados por Lighthouse.",
  },
};

export const esAuditCopy: AuditCopy = {
  meta: {
    title: "Auditoría de Oportunidades Web | LV Branding",
    description: "Descubre dónde tu sitio aporta claridad, confianza, visibilidad y acción, y qué merece atención primero.",
    productName: "Auditoría de Oportunidades Web de LV",
    shortName: "Auditoría de Oportunidades Web",
    mobileName: "Auditoría Web",
    descriptor: "Una auditoría gratuita de claridad, experiencia y visibilidad por LV Branding",
  },
  common: {
    language: "Idioma",
    english: "English",
    spanish: "Español",
    back: "Atrás",
    continue: "Continuar",
    startOver: "Empezar de nuevo",
    cancel: "Cancelar",
    optional: "opcional",
    website: "Sitio web",
    close: "Cerrar",
    yes: "Sí",
    no: "No",
  },
  landing: {
    eyebrow: "Auditoría gratuita de claridad web",
    heading: "Tu sitio siempre está comunicando algo.",
    emphasis: "Asegúrate de que sea lo correcto.",
    body: "Descubre dónde tu sitio ayuda al negocio, dónde genera fricción y qué merece atención primero.",
    urlLabel: "Ingresa la dirección de un sitio web público",
    urlPlaceholder: "tusitioweb.com",
    cta: "Auditar Mi Sitio",
    workingCta: "Verificando dirección…",
    reassurance: "Sin cuenta · sin pedir email · cerca de 2 minutos",
    acceptTerms: "Confirmo que puedo enviar este sitio público para una auditoría automatizada.",
    termsRequired: "Confirma que tienes permiso para auditar este sitio público antes de continuar.",
    termsLead: "Consulta los",
    terms: "términos de la auditoría",
    termsBody: "Envía solo un sitio público que tengas permiso de revisar. La auditoría realiza solicitudes automáticas limitadas a páginas públicas, conserva señales normalizadas hasta 30 días y sirve para planificación; no es una certificación, opinión legal, declaración de conformidad de accesibilidad ni garantía de aparecer en buscadores o productos de IA.",
    privacy: "Revisamos solo páginas públicas. Las URLs y los datos compartidos siguen las prácticas de privacidad de LV Branding.",
    sampleLead: "¿Quieres ver el informe antes de hacer una auditoría?",
    sampleCta: "Explorar un resultado de muestra",
    representative: "Enfocada, no abrumadora",
    representativeBody: "Revisamos la página enviada y hasta cuatro páginas útiles del mismo dominio, no un rastreo interminable.",
    evidence: "Evidencia transparente",
    evidenceBody: "Cada hallazgo indica si fue verificado, inferido, autorreportado o requiere revisión experta.",
    useful: "Un plan, no una lista de errores",
    usefulBody: "El resultado comienza con las tres oportunidades con mayor potencial para mejorar claridad, visibilidad o acción.",
    dimensionEyebrow: "Un sitio. Cinco perspectivas de negocio.",
    dimensionHeading: "Más útil que un índice SEO genérico.",
    dimensionBody: "El Índice de Oportunidad Web combina señales observables con reglas transparentes. Es una herramienta de planificación, no una certificación ni una promesa de aparecer en buscadores o productos de IA.",
    stepsHeading: "Qué sucede después de ingresar tu sitio",
    steps: [
      { number: "01", title: "Agrega contexto del negocio", body: "Cuéntanos qué debe lograr el sitio y a quién debe llegar primero." },
      { number: "02", title: "Revisamos señales públicas", body: "La auditoría examina páginas representativas, estructura, contenido y señales móviles y técnicas." },
      { number: "03", title: "Recibe un plan priorizado", body: "Consulta cinco índices, evidencia clara y las tres acciones que merecen atención primero." },
    ],
    badges: ["Solo páginas públicas", "Resultado sin email", "English + Español"],
  },
  context: {
    progress: "Un poco de contexto mejora el resultado",
    heading: "¿Qué necesita lograr este sitio para el negocio?",
    body: "La automatización puede leer una página, pero no conoce su estrategia. Estas respuestas calibran los hallazgos de posicionamiento y conversión sin reemplazar la evidencia observada.",
    businessType: "¿Qué tipo de negocio u organización es?",
    audience: "¿Quién debe entender la oferta primero?",
    audienceHint: "Una respuesta breve y específica funciona mejor.",
    audiencePlaceholder: "Por ejemplo: líderes de operaciones en empresas manufactureras en crecimiento",
    purpose: "¿Cuál es la función principal del sitio?",
    conversionAction: "¿Cuál es la acción más importante que debe tomar una visita?",
    differentiation: "¿Una persona nueva puede explicar qué hace diferente al negocio después de ver la página principal?",
    differentiationHint: "Tu respuesta honesta ayuda a separar la fricción de contenido de los problemas técnicos.",
    expectedResults: "¿El sitio está produciendo las consultas o acciones que espera el negocio?",
    expectedResultsHint: "Este es contexto autorreportado, no un hallazgo técnico.",
    lastReviewed: "¿Cuándo se revisaron deliberadamente la estructura o el contenido por última vez?",
    required: "Completa esta pregunta.",
    submit: "Iniciar la Auditoría",
    businessTypes: [
      { value: "professional-services", label: "Servicios profesionales" },
      { value: "local-business", label: "Negocio local" },
      { value: "b2b", label: "Empresa B2B" },
      { value: "ecommerce", label: "Comercio electrónico" },
      { value: "nonprofit", label: "Organización sin fines de lucro" },
      { value: "platform", label: "Plataforma o portal" },
      { value: "other", label: "Otro tipo" },
    ],
    purposes: [
      { value: "generate-leads", label: "Generar prospectos", hint: "Crear conversaciones calificadas" },
      { value: "sell", label: "Vender", hint: "Impulsar compras o suscripciones" },
      { value: "book", label: "Reservar", hint: "Agendar servicios o citas" },
      { value: "educate", label: "Educar", hint: "Explicar un problema, oferta o punto de vista" },
      { value: "partners", label: "Atraer aliados", hint: "Generar credibilidad con colaboradores o financiadores" },
      { value: "support", label: "Atender clientes", hint: "Ayudar a clientes actuales a completar una tarea" },
    ],
    conversionActions: [
      { value: "contact", label: "Contactar al equipo" },
      { value: "request-quote", label: "Solicitar cotización" },
      { value: "book", label: "Reservar o agendar" },
      { value: "buy", label: "Comprar" },
      { value: "sign-up", label: "Registrarse" },
      { value: "use-tool", label: "Usar una herramienta o portal" },
      { value: "call", label: "Llamar" },
      { value: "other", label: "Otra acción" },
    ],
    ternary: [
      { value: "yes", label: "Sí" },
      { value: "no", label: "No" },
      { value: "unsure", label: "No estoy seguro" },
    ],
    reviewRecency: [
      { value: "six-months", label: "En los últimos 6 meses" },
      { value: "one-year", label: "Hace 6–12 meses" },
      { value: "two-years", label: "Hace 1–2 años o más" },
      { value: "unknown", label: "No estoy seguro" },
    ],
  },
  analyzing: {
    eyebrow: "Auditoría en curso",
    heading: "Estamos leyendo el sitio como podría hacerlo un cliente.",
    body: "Esto puede tomar un momento. Mantén esta pestaña abierta; no necesitas actualizarla.",
    stages: ["Conectando de forma segura", "Revisando páginas representativas", "Comprobando señales móviles y técnicas", "Creando tu plan de oportunidades"],
    patience: "La mayoría termina en menos de un minuto. Algunos sitios o pruebas de PageSpeed tardan más.",
    failedHeading: "No pudimos completar esta auditoría.",
    failedBody: "El sitio puede bloquear revisiones automáticas, devolver contenido no compatible o el servicio puede no estar desplegado todavía.",
    tryAgain: "Intentar de nuevo",
    sampleInstead: "Ver un resultado de muestra",
  },
  results: {
    sampleBanner: "Informe de muestra",
    sampleBannerBody: "Estos son datos representativos de demostración para un sitio ficticio. No se consultó un sitio real.",
    eyebrow: "Tu informe de oportunidades web",
    reportFor: "Informe para",
    auditedOn: "Auditado",
    pagesAnalyzed: (count) => `${count} ${count === 1 ? "página representativa analizada" : "páginas representativas analizadas"}`,
    pageLanguage: "Idioma detectado del sitio",
    pagePreview: "Vista previa de la página enviada",
    pagePreviewNote: "Creada con el título y encabezado encontrados; no es una captura visual.",
    pageScreenshotNote: "Captura móvil suministrada por Lighthouse al realizar la auditoría.",
    pageScreenshotAlt: "Captura móvil del sitio enviado",
    englishPage: "Inglés",
    spanishPage: "Español",
    unknownPage: "No confirmado",
    opportunityScore: "Índice de Oportunidad Web",
    outOf: "de 100",
    coverage: "Cobertura de evidencia",
    coverageShort: "medido",
    coverageBody: "Las pruebas no disponibles se excluyen del cálculo. Reducen la cobertura, no tu índice.",
    diagnosis: {
      strong: "Una base sólida con oportunidades específicas que conviene proteger y optimizar.",
      friction: "El sitio funciona, pero la fricción evitable puede costar claridad, visibilidad o acción.",
      constrained: "Varios problemas probablemente limitan la confianza, el descubrimiento o la conversión.",
      rebuild: "Los problemas estructurales pueden costar más al parchearlos que al replantear la experiencia.",
    },
    dimensionHeading: "Cinco perspectivas de una misma experiencia",
    dimensionBody: "Cada índice usa solo pruebas aplicables y medidas. Abre los hallazgos para ver exactamente qué movió cada cifra.",
    working: "Lo que funciona",
    friction: "Lo que genera fricción",
    noStrength: "Ninguna verificación medida alcanzó todavía un resultado completo en esta dimensión.",
    noFriction: "Ninguna verificación medida generó fricción puntuada en esta dimensión.",
    nextAction: "Acción recomendada",
    protectDimension: "Conserva intacto el patrón medido más sólido y revísalo cada vez que cambie esta experiencia.",
    priorityEyebrow: "Tu plan de oportunidades",
    priorityHeading: "Comienza por los movimientos que más importan.",
    priorityBody: "La prioridad se ordena aparte del índice según severidad, impacto, confianza y esfuerzo.",
    priorityHeadingClear: "Protege la base que ya tienes.",
    priorityBodyClear: "Ninguna verificación medida generó una acción de reparación. Conserva el patrón más sólido y revisa por separado la evidencia faltante.",
    fixNow: "Resolver ahora",
    fixNowHint: "Alto impacto · esfuerzo bajo o moderado",
    planNext: "Planear después",
    planNextHint: "Una oportunidad mayor que necesita coordinación",
    protect: "Proteger",
    protectHint: "Una fortaleza que debe sobrevivir futuros cambios",
    fullFindings: "Ver todos los hallazgos",
    fullFindingsBody: "Consulta cada prueba, su tipo de evidencia y la regla que la respalda.",
    findingsCount: (count) => `${count} ${count === 1 ? "hallazgo" : "hallazgos"}`,
    notMeasured: "No medido",
    pageScope: "Alcance y cobertura de la auditoría",
    analyzed: "Páginas analizadas",
    labUnavailable: "PageSpeed no estuvo disponible. Las pruebas de rendimiento fueron excluidas del denominador.",
    pageScopeIncomplete: "No fue posible recuperar una o más páginas representativas. Esas ausencias redujeron la cobertura, no el índice.",
    aiDisclaimer: "La Preparación para Respuestas de IA evalúa accesibilidad y claridad de contenido. No predice ni garantiza aparecer en ningún producto de IA.",
    runAnother: "Auditar otro sitio",
    sampleCtaHeading: "Ahora haz tuyo el informe.",
    sampleCtaBody: "Aplica la misma revisión transparente a tu sitio público. El resultado completo está disponible sin cuenta ni dirección de email.",
    sampleCtaAction: "Auditar Mi Sitio",
  },
  dimensions: {
    experience: { label: "Experiencia y Usabilidad", short: "Experiencia", description: "Qué tan fácil es navegar, recorrer, comprender e interactuar desde móvil." },
    positioning: { label: "Posicionamiento y Conversión", short: "Posicionamiento", description: "Qué tan bien comunica relevancia, diferencia, evidencia y el siguiente paso." },
    search: { label: "Visibilidad en Búsqueda", short: "Búsqueda", description: "Si los buscadores pueden interpretar, indexar y conectar el contenido clave." },
    aiReadiness: { label: "Preparación para Respuestas de IA", short: "Preparación IA", description: "Si el contenido es explícito, estructurado, respaldado y fácil de interpretar." },
    technical: { label: "Salud Técnica", short: "Técnica", description: "Señales de respuesta, HTML, seguridad, rendimiento móvil y estabilidad." },
  },
  bands: {
    strong: { label: "Base sólida", meaning: "Protege lo que funciona y optimiza oportunidades específicas" },
    friction: { label: "Funciona, con fricción", meaning: "Es funcional, pero puede perder claridad, visibilidad o conversiones" },
    constrained: { label: "Crecimiento limitado", meaning: "Varios problemas probablemente limitan confianza, descubrimiento o acción" },
    rebuild: { label: "Territorio de rediseño", meaning: "Puede costar más parchar los problemas estructurales que replantearlos" },
  },
  evidence: {
    verified: { label: "Verificado", description: "Observado directamente en la página, respuesta o datos de auditoría." },
    inferred: { label: "Inferido", description: "Determinado mediante una regla transparente de contenido o interfaz." },
    selfReported: { label: "Autorreportado", description: "Basado en el contexto que compartiste." },
    needsReview: { label: "Requiere revisión experta", description: "No se puede juzgar responsablemente solo con automatización." },
  },
  outcomes: { pass: "Funciona", partial: "Oportunidad", fail: "Necesita atención", notMeasured: "No medido" },
  rules,
  routes: {
    improve: { label: "Mejorar Este Sitio", heading: "Vale la pena mejorar este sitio con precisión.", body: "La base es viable. Conviene resolver las brechas de mayor valor sin alterar lo que ya funciona.", action: "Mejorar Este Sitio" },
    ux: { label: "Planear una Mejora UX/UI", heading: "La estructura puede trabajar mejor para sus visitantes.", body: "Una mejora UX/UI enfocada puede eliminar fricción y conservar las partes viables del sitio actual.", action: "Planear una Mejora UX/UI" },
    redesign: { label: "Explorar un Rediseño Web", heading: "Los problemas están conectados, no aislados.", body: "Las limitaciones de posicionamiento, experiencia y técnica apuntan a un rediseño coordinado en lugar de una serie de parches.", action: "Explorar un Rediseño Web" },
    platform: { label: "Hablar de una Plataforma Web", heading: "El sitio puede necesitar hacer más que publicar páginas.", body: "Un flujo de trabajo, portal o tarea interactiva puede requerir una plataforma personalizada junto con la experiencia pública.", action: "Hablar de una Plataforma Web" },
  },
  lead: {
    supporting: "La auditoría encontró dónde está la fricción. LV Branding puede ayudarte a decidir qué reparar, qué rediseñar y qué no vale la pena tocar.",
    openForm: "Pedir ayuda a LV Branding",
    heading: "Cuéntanos a dónde quieres llegar.",
    body: "El sitio y el contexto de la auditoría ya están incluidos. Solo necesitamos lo suficiente para dirigir bien la conversación.",
    name: "Nombre",
    email: "Email de trabajo",
    company: "Empresa",
    pathway: "Tipo de ayuda preferida",
    timeline: "Plazo",
    context: "Contexto del proyecto",
    contextPlaceholder: "¿Hay algo importante sobre el sitio, el equipo o la próxima decisión?",
    consent: "Acepto que LV Branding use esta auditoría y mis datos de contacto para responder a esta solicitud.",
    disclosure: "Enviamos la URL, los índices, las oportunidades principales, el tipo de ayuda, el plazo y los datos ingresados aquí.",
    submit: "Enviar Mi Solicitud",
    submitting: "Enviando…",
    successHeading: "Tu auditoría llegó al equipo indicado.",
    successBody: "Revisaremos el contexto y responderemos en un día hábil. Tu resultado seguirá disponible en este navegador.",
    error: "No pudimos enviar la solicitud. Intenta de nuevo o escribe a luis@lvbranding.com.",
    required: "Completa este campo.",
    invalidEmail: "Ingresa un email de trabajo válido.",
    timelines: [
      { value: "now", label: "Ahora" },
      { value: "one-three", label: "1–3 meses" },
      { value: "three-six", label: "3–6 meses" },
      { value: "exploring", label: "Explorando" },
    ],
  },
  errors: {
    urlRequired: "Ingresa la dirección de un sitio para continuar.",
    urlInvalid: "Ingresa una dirección válida, por ejemplo sitio.com.",
    urlPublicOnly: "Usa un sitio público http o https, no localhost ni una dirección de red privada.",
    contextRequired: "Completa el contexto requerido para interpretar el sitio responsablemente.",
    auditUnavailable: "El servicio de auditoría no está disponible ahora.",
    rateLimited: "Este sitio o conexión alcanzó el límite de auditorías. Intenta de nuevo más tarde.",
    siteUnreachable: "No pudimos localizar o acceder a este sitio. Confirma la dirección y que esté disponible públicamente.",
    siteTimeout: "El sitio tardó demasiado en responder. Intenta de nuevo cuando funcione con normalidad.",
    unsupportedContent: "Esa dirección no devolvió una página HTML pública que podamos auditar.",
    unhealthyResponse: "La página enviada respondió con un error y no se pudo auditar.",
    responseTooLarge: "La página enviada supera el tamaño que esta auditoría representativa puede procesar de forma segura.",
    redirectFailed: "No pudimos seguir de forma segura la ruta de redirección del sitio.",
    resultMissing: "Este resultado no está disponible en este navegador. Inicia una auditoría nueva.",
    resultExpired: "Este enlace privado de resultados no es válido o ya venció.",
    resultVersionUnsupported: "Este resultado usa una versión anterior y no se puede recalcular de forma segura. Inicia una auditoría nueva para obtener un informe actual.",
    resultUnavailable: "No pudimos cargar este resultado ahora. Es posible que tu enlace privado siga vigente.",
    retryResult: "Intentar cargar de nuevo",
  },
  footer: "Hecho con cuidado por LV Branding",
};
