import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { jsPDF } from "jspdf";
import { toPng } from "html-to-image";
import { addEdge, Background, BackgroundVariant, Controls, getNodesBounds, getViewportForBounds, MiniMap, ReactFlow, type Connection, type ReactFlowInstance, type Viewport, useEdgesState, useNodesState } from "@xyflow/react";
import "@xyflow/react/dist/style.css";
import { ArrowDownToLine, ArrowLeft, ArrowUpToLine, Bot, Check, ChevronLeft, ChevronRight, CircleDollarSign, Cloud, CloudOff, Download, FileText, Focus, Group, Image as ImageIcon, Layers3, Loader2, Maximize2, Palette, Plus, Save, Sparkles, Type, Ungroup, Upload, WifiOff } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { CreativeNodeActionsProvider, creativeNodeTypes } from "@/components/creative-canvas/CreativeNodes";
import { toast } from "@/hooks/use-toast";
import { useLanguage } from "@/hooks/useLanguage";
import { useBrandContext, useCreativeAssets, useCreativeCanvas, useCreativeGenerations, useCreateDecision, useCreativeProviderStatus, useCreativeUsage, useGenerateCreative, useSaveBrandContext, useSaveCreativeCanvas, useUploadCreativeAsset } from "@/hooks/useCreativeCanvas";
import { flowToScene, sceneToFlow, type CreativeFlowEdge, type CreativeFlowNode, type CreativeNodeData } from "@/lib/creative-canvas/react-flow-adapter";
import { createEmptyScene, makeIdempotencyKey, restoreScene, serializeScene, type CreativeSceneDocument } from "@/lib/creative-canvas/scene";
import type { BrandContext, CreativeDecision, CreativeNodeType, CreativeOperation, CreativeProvider } from "@/lib/creative-canvas/types";

const NODE_TOOLS: Array<{ type: CreativeNodeType; label: string; icon: typeof Type; title: string; body: string; accent?: string; size?: [number, number] }> = [
  { type: "text", label: "Text", icon: Type, title: "Headline concept", body: "Write directly in this block." },
  { type: "reference", label: "Reference", icon: ImageIcon, title: "Visual reference", body: "Add why this reference matters." },
  { type: "brand_context", label: "Brand", icon: Layers3, title: "Brand context", body: "Open Brand Context in the right panel to define the project source of truth.", size: [360, 250] },
  { type: "creative_direction", label: "Direction", icon: Sparkles, title: "Creative Direction 01", body: "Strategic rationale\n\nVisual narrative\n\nKeywords\n\nInternal notes", size: [440, 330] },
  { type: "palette", label: "Palette", icon: Palette, title: "Primary red", body: "Brand accent", size: [260, 210] },
  { type: "typography", label: "Type", icon: FileText, title: "Fira Sans", body: "Role: Primary sans serif\nWeights: 400, 500, 600, 700\nUsage: Clear, confident communications" },
  { type: "conversation", label: "AI chat", icon: Bot, title: "AI conversation", body: "Preserve the instruction and the visible assistant response here." },
  { type: "decision", label: "Decision", icon: Check, title: "Decision", body: "Status, owner, rationale, and next revision." },
  { type: "export_frame", label: "Export", icon: Maximize2, title: "Presentation frame", body: "Arrange approved work inside this export area.", size: [900, 600] },
];

const AI_ACTIONS: Array<{ value: CreativeOperation; label: string }> = [
  { value: "campaign_concept", label: "Campaign concept" }, { value: "write_copy", label: "Write copy" }, { value: "rewrite", label: "Rewrite" }, { value: "shorten", label: "Shorten" }, { value: "expand", label: "Expand" }, { value: "adapt_en_es", label: "Adapt EN → ES" }, { value: "adapt_es_en", label: "Adapt ES → EN" }, { value: "generate_image", label: "Generate image" }, { value: "edit_image", label: "Edit image" }, { value: "variations", label: "Generate variations" }, { value: "visual_critique", label: "Analyze direction" }, { value: "compare_concepts", label: "Compare concepts" }, { value: "recommend_direction", label: "Recommend direction" }, { value: "creative_rationale", label: "Creative rationale" }, { value: "production_prompt", label: "Production prompt" },
];

const BRAND_FIELDS: Array<{ key: keyof BrandContext; label: string; placeholder: string }> = [
  { key: "brandName", label: "Brand or client", placeholder: "Name" }, { key: "businessDescription", label: "Business description", placeholder: "What the business does and why it matters" }, { key: "objective", label: "Project objective", placeholder: "The change this work must create" }, { key: "audiences", label: "Target audiences", placeholder: "Primary and secondary audiences" }, { key: "positioning", label: "Positioning", placeholder: "Distinct position in the market" }, { key: "valueProposition", label: "Value proposition", placeholder: "Core value promised" }, { key: "personality", label: "Brand personality", placeholder: "Traits and behaviors" }, { key: "voiceTone", label: "Voice and tone", placeholder: "How the brand should sound" }, { key: "requiredMessages", label: "Required messages", placeholder: "Messages every direction must carry" }, { key: "visualPrinciples", label: "Visual principles", placeholder: "Composition, mood, lighting, style" }, { key: "approvedColors", label: "Approved colors", placeholder: "Named colors and HEX values" }, { key: "typography", label: "Typography guidance", placeholder: "Typefaces, roles, weights" }, { key: "requiredElements", label: "Required visual elements", placeholder: "Products, logos, settings, people" }, { key: "prohibitedElements", label: "Prohibited elements", placeholder: "Never include" }, { key: "avoidWords", label: "Words or phrases to avoid", placeholder: "Language exclusions" }, { key: "competitors", label: "Competitors", placeholder: "Competitive set" }, { key: "languages", label: "Languages", placeholder: "English, Spanish" }, { key: "market", label: "Market or location", placeholder: "Houston, US Hispanic market, etc." }, { key: "compliance", label: "Legal or compliance notes", placeholder: "Mandatory qualifications and disclaimers" }, { key: "additionalContext", label: "Additional context", placeholder: "Anything else the team should know" },
];

type FlowSnapshot = { nodes: CreativeFlowNode[]; edges: CreativeFlowEdge[] };
const cloneSnapshot = (nodes: CreativeFlowNode[], edges: CreativeFlowEdge[]): FlowSnapshot => ({ nodes: structuredClone(nodes), edges: structuredClone(edges) });
// `savedAt` is stamped with the current time every time a scene is built, so a
// straight comparison of two serializations never matches. The fingerprint is
// everything that actually describes the document, minus that timestamp.
const sceneFingerprint = (scene: CreativeSceneDocument): string => {
  const { savedAt: _savedAt, ...rest } = scene;
  return JSON.stringify(rest);
};
const newId = (prefix = "node") => `${prefix}-${crypto.randomUUID()}`;
function downloadBlob(blob: Blob, filename: string) { const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click(); URL.revokeObjectURL(url); }

function makeNode(type: CreativeNodeType, point: { x: number; y: number }, options: Partial<CreativeNodeData> & { width?: number; height?: number } = {}): CreativeFlowNode {
  const tool = NODE_TOOLS.find((item) => item.type === type); const width = options.width ?? tool?.size?.[0] ?? 320; const height = options.height ?? tool?.size?.[1] ?? 220;
  return { id: newId(), type, position: { x: point.x - width / 2, y: point.y - height / 2 }, selected: true, style: { width, height }, data: { nodeType: type, title: options.title ?? tool?.title ?? "Untitled", body: options.body ?? tool?.body ?? "", accent: options.accent ?? tool?.accent ?? "#CB2039", assetId: options.assetId ?? "", assetUrl: options.assetUrl ?? "", includeInContext: options.includeInContext ?? true, status: options.status ?? "draft" } };
}

function demoScene(): CreativeSceneDocument {
  const data: Array<[CreativeNodeType, number, number, number, number, string, string, string]> = [
    ["brand_context",-610,-270,360,280,"Soluna Market","Objective\nBuild awareness for a seasonal market launch.\n\nAudience\nBilingual Houston families and independent makers.\n\nVoice\nWarm, confident, specific.","#CB2039"],
    ["creative_direction",-180,-300,430,320,"01 · Made Here, Shared Here","Turn local provenance into an invitation to belong.\n\nWarm documentary moments, tactile products, natural light.\n\nLOCAL · GENEROUS · HUMAN","#CB2039"],
    ["creative_direction",320,-300,430,320,"02 · Two Languages, One Table","Treat bilingual culture as lived connection, not translation.\n\nGraphic table compositions with paired messages.\n\nSOCIAL · BOLD · WELCOMING","#CB2039"],
    ["palette",-600,90,255,205,"Soluna Terracotta","Primary warmth","#C75B3A"], ["palette",-300,90,255,205,"Market Marigold","Optimistic accent","#F2B134"],
    ["text",10,90,360,235,"Made here. Shared here.","Hecho aquí. Compartido aquí.\n\nA bilingual campaign idea built from one shared intention.","#CB2039"],
    ["reference",430,90,320,235,"Shared-table reference","Use for human energy and composition. Avoid staged stock-photo cues.","#CB2039"],
  ];
  return serializeScene({ schemaVersion: 1, edges: [], viewport: { x: 505, y: 375, zoom: .72 }, nodes: data.map(([type,x,y,width,height,title,body,accent]) => ({ id: newId(), type, position: { x, y }, size: { width, height }, title, body, accent, includeInContext: true, status: "draft" })) });
}

export default function CreativeCanvasWorkspace() {
  const { canvasId } = useParams(); const { language } = useLanguage(); const { data: canvas, isLoading, isError } = useCreativeCanvas(canvasId);
  const { data: brandRecord } = useBrandContext(canvas?.project_id); const { data: assets = [] } = useCreativeAssets(canvas?.project_id); const { data: generations = [] } = useCreativeGenerations(canvasId); const { data: usage } = useCreativeUsage(canvas?.project_id); const { data: providerStatusData } = useCreativeProviderStatus();
  const providerStatus = providerStatusData ?? (["openai", "google", "anthropic"] as const).map((id) => ({ id, enabled: false, capabilities: [] }));
  const createDecision = useCreateDecision(); const saveCanvas = useSaveCreativeCanvas(canvas); const saveBrand = useSaveBrandContext(canvas?.project_id, canvas?.org_id); const uploadAsset = useUploadCreativeAsset(canvas?.project_id, canvas?.org_id); const generate = useGenerateCreative();
  const [nodes, setNodes, onNodesChange] = useNodesState<CreativeFlowNode>([]); const [edges, setEdges, onEdgesChange] = useEdgesState<CreativeFlowEdge>([]); const [flow, setFlow] = useState<ReactFlowInstance<CreativeFlowNode, CreativeFlowEdge> | null>(null);
  const viewportRef = useRef<Viewport>({ x: 0, y: 0, zoom: 1 }); const nodesRef = useRef(nodes); const edgesRef = useRef(edges); nodesRef.current = nodes; edgesRef.current = edges;
  const hydrated = useRef(false); const lastSavedScene = useRef<string>(""); const loadedCanvasId = useRef<string | null>(null); const history = useRef<{ past: FlowSnapshot[]; future: FlowSnapshot[] }>({ past: [], future: [] }); const clipboard = useRef<CreativeFlowNode[]>([]);
  const [leftOpen, setLeftOpen] = useState(true); const [rightOpen, setRightOpen] = useState(true); const [pendingScene, setPendingScene] = useState<CreativeSceneDocument | null>(null); const [saveState, setSaveState] = useState<"saved" | "unsaved" | "saving" | "error" | "offline">("saved"); const [exporting, setExporting] = useState<"png" | "pdf" | null>(null);
  const [instruction, setInstruction] = useState(""); const [operation, setOperation] = useState<CreativeOperation>("campaign_concept"); const [provider, setProvider] = useState<CreativeProvider>("auto"); const [brandDraft, setBrandDraft] = useState<BrandContext>({}); const fileInput = useRef<HTMLInputElement>(null);
  const selection = useMemo(() => nodes.filter((node) => node.selected), [nodes]); const assetUrls = useMemo(() => new Map(assets.filter((asset) => asset.signedUrl).map((asset) => [asset.id, asset.signedUrl!])), [assets]);

  useEffect(() => { if (brandRecord?.content) setBrandDraft(brandRecord.content); else if (canvas?.projects) setBrandDraft({ brandName: canvas.projects.client_name ?? "", objective: canvas.projects.description ?? "" }); }, [brandRecord, canvas?.projects]);
  useEffect(() => { const online = () => setSaveState((state) => state === "offline" ? "unsaved" : state); const offline = () => setSaveState("offline"); window.addEventListener("online", online); window.addEventListener("offline", offline); return () => { window.removeEventListener("online", online); window.removeEventListener("offline", offline); }; }, []);
  useEffect(() => {
    if (!canvas || loadedCanvasId.current === canvas.id) return; loadedCanvasId.current = canvas.id; hydrated.current = false; history.current = { past: [], future: [] };
    let scene = restoreScene(canvas.scene_document) ?? createEmptyScene(); if (!scene.nodes.length && canvas.projects.name === "LV Creative Canvas™ Demo: Bilingual Brand Campaign") scene = demoScene();
    const adapted = sceneToFlow(scene, assetUrls); setNodes(adapted.nodes); setEdges(adapted.edges); viewportRef.current = adapted.viewport; lastSavedScene.current = sceneFingerprint(serializeScene(scene));
    requestAnimationFrame(() => { void flow?.setViewport(adapted.viewport); hydrated.current = true; if (scene.nodes.length && !restoreScene(canvas.scene_document)) setPendingScene(scene); });
  }, [assetUrls, canvas, flow, setEdges, setNodes]);
  useEffect(() => { if (!assetUrls.size) return; setNodes((current) => current.map((node) => node.data.assetId && assetUrls.has(node.data.assetId) ? { ...node, data: { ...node.data, assetUrl: assetUrls.get(node.data.assetId)! } } : node)); }, [assetUrls, setNodes]);
  // React Flow emits change events for selection and measurement, not just real
  // edits, so this effect runs when nothing about the saved document differs.
  // Comparing against the last persisted serialization keeps idle clicking from
  // writing the whole scene back and inflating the optimistic-version counter.
  useEffect(() => {
    if (!hydrated.current || !canvas) return;
    const next = flowToScene(nodes, edges, viewportRef.current);
    if (sceneFingerprint(serializeScene(next)) === lastSavedScene.current) return;
    setPendingScene(next);
    setSaveState(navigator.onLine ? "unsaved" : "offline");
  }, [canvas, edges, nodes]);
  useEffect(() => { if (!pendingScene || !canvas || !navigator.onLine) return; const sceneToSave = pendingScene; const timer = window.setTimeout(async () => { setSaveState("saving"); try { const encoded = serializeScene(sceneToSave); await saveCanvas.mutateAsync(encoded as unknown as Record<string, unknown>); lastSavedScene.current = sceneFingerprint(encoded); setPendingScene((current) => current === sceneToSave ? null : current); setSaveState("saved"); } catch (error) { setSaveState("error"); toast({ title: "Canvas was not saved", description: error instanceof Error ? error.message : "Try again.", variant: "destructive" }); } }, 1200); return () => window.clearTimeout(timer); }, [canvas, pendingScene, saveCanvas.mutateAsync]);

  const recordHistory = useCallback(() => { history.current.past.push(cloneSnapshot(nodesRef.current, edgesRef.current)); if (history.current.past.length > 80) history.current.past.shift(); history.current.future = []; }, []);
  const restoreSnapshot = useCallback((snapshot: FlowSnapshot) => { setNodes(snapshot.nodes); setEdges(snapshot.edges); }, [setEdges, setNodes]);
  const undo = useCallback(() => { const previous = history.current.past.pop(); if (!previous) return; history.current.future.push(cloneSnapshot(nodesRef.current, edgesRef.current)); restoreSnapshot(previous); }, [restoreSnapshot]);
  const redo = useCallback(() => { const next = history.current.future.pop(); if (!next) return; history.current.past.push(cloneSnapshot(nodesRef.current, edgesRef.current)); restoreSnapshot(next); }, [restoreSnapshot]);
  const updateNodeData = useCallback((id: string, values: Partial<CreativeNodeData>) => { recordHistory(); setNodes((current) => current.map((node) => node.id === id ? { ...node, data: { ...node.data, ...values } } : node)); }, [recordHistory, setNodes]);
  const canvasCenter = useCallback(() => flow?.screenToFlowPosition({ x: window.innerWidth / 2, y: window.innerHeight / 2 }) ?? { x: 0, y: 0 }, [flow]);
  const addNode = useCallback((type: CreativeNodeType, options: Partial<CreativeNodeData> & { width?: number; height?: number } = {}, point = canvasCenter()) => { recordHistory(); const node = makeNode(type, point, options); setNodes((current) => [...current.map((item) => ({ ...item, selected: false })), node]); return node.id; }, [canvasCenter, recordHistory, setNodes]);
  const connect = useCallback((connection: Connection) => { recordHistory(); setEdges((current) => addEdge({ ...connection, id: newId("edge"), type: "smoothstep" }, current)); }, [recordHistory, setEdges]);
  const deleteSelection = useCallback(() => { if (!selection.length) return; recordHistory(); const ids = new Set(selection.map((node) => node.id)); setNodes((current) => current.filter((node) => !ids.has(node.id) && (!node.parentId || !ids.has(node.parentId)))); setEdges((current) => current.filter((edge) => !ids.has(edge.source) && !ids.has(edge.target))); }, [recordHistory, selection, setEdges, setNodes]);
  const copySelection = useCallback(() => { clipboard.current = structuredClone(selection); }, [selection]);
  const pasteSelection = useCallback(() => { if (!clipboard.current.length) return; recordHistory(); const idMap = new Map(clipboard.current.map((node) => [node.id, newId()])); const pasted = clipboard.current.map((node) => ({ ...node, id: idMap.get(node.id)!, parentId: node.parentId ? idMap.get(node.parentId) : undefined, position: { x: node.position.x + 36, y: node.position.y + 36 }, selected: true })); setNodes((current) => [...current.map((node) => ({ ...node, selected: false })), ...pasted]); clipboard.current = structuredClone(pasted); }, [recordHistory, setNodes]);
  const duplicateSelection = useCallback(() => { copySelection(); pasteSelection(); }, [copySelection, pasteSelection]);
  const changeOrder = useCallback((direction: 1 | -1) => { if (!selection.length) return; recordHistory(); setNodes((current) => current.map((node) => node.selected ? { ...node, zIndex: (node.zIndex ?? 0) + direction } : node)); }, [recordHistory, selection.length, setNodes]);
  const groupSelection = useCallback(() => { const chosen = selection.filter((node) => !node.parentId); if (chosen.length < 2) return; recordHistory(); const bounds = getNodesBounds(chosen); const groupId = newId("frame"); const padding = 42; const frame = makeNode("export_frame", { x: bounds.x + bounds.width / 2, y: bounds.y + bounds.height / 2 }, { title: "Creative direction frame", body: "Grouped workspace objects", width: bounds.width + padding * 2, height: bounds.height + padding * 2 }); frame.id = groupId; frame.position = { x: bounds.x - padding, y: bounds.y - padding }; frame.selected = true; frame.zIndex = -1; setNodes((current) => [frame, ...current.map((node) => chosen.some((item) => item.id === node.id) ? { ...node, parentId: groupId, extent: "parent" as const, position: { x: node.position.x - frame.position.x, y: node.position.y - frame.position.y }, selected: false, zIndex: 1 } : { ...node, selected: false })]); }, [recordHistory, selection, setNodes]);
  const ungroupSelection = useCallback(() => { const groups = selection.filter((node) => nodes.some((child) => child.parentId === node.id)); if (!groups.length) return; recordHistory(); const byId = new Map(groups.map((group) => [group.id, group])); const ids = new Set(byId.keys()); setNodes((current) => current.filter((node) => !ids.has(node.id)).map((node) => node.parentId && byId.has(node.parentId) ? { ...node, parentId: undefined, extent: undefined, position: { x: node.position.x + byId.get(node.parentId)!.position.x, y: node.position.y + byId.get(node.parentId)!.position.y }, selected: true } : node)); }, [nodes, recordHistory, selection, setNodes]);

  useEffect(() => { const keydown = (event: KeyboardEvent) => { const element = event.target as HTMLElement; if (["INPUT", "TEXTAREA", "SELECT"].includes(element.tagName) || element.isContentEditable) return; const command = event.metaKey || event.ctrlKey; if (command && event.key.toLowerCase() === "z") { event.preventDefault(); event.shiftKey ? redo() : undo(); } else if (command && event.key.toLowerCase() === "y") { event.preventDefault(); redo(); } else if (command && event.key.toLowerCase() === "c") { event.preventDefault(); copySelection(); } else if (command && event.key.toLowerCase() === "v") { event.preventDefault(); pasteSelection(); } else if (command && event.key.toLowerCase() === "d") { event.preventDefault(); duplicateSelection(); } else if (event.key === "Delete" || event.key === "Backspace") { event.preventDefault(); deleteSelection(); } }; window.addEventListener("keydown", keydown); return () => window.removeEventListener("keydown", keydown); }, [copySelection, deleteSelection, duplicateSelection, pasteSelection, redo, undo]);

  const upload = async (files: FileList | File[], point?: { x: number; y: number }) => { let offset = 0; for (const file of Array.from(files)) { try { const asset = await uploadAsset.mutateAsync({ file, sourceType: "reference" }); addNode("reference", { title: asset.original_filename, body: "Reference notes", assetId: asset.id, assetUrl: asset.signedUrl ?? "", width: 360, height: 360 }, point ? { x: point.x + offset, y: point.y + offset } : undefined); offset += 36; } catch (error) { toast({ title: "Upload failed", description: error instanceof Error ? error.message : "Try again.", variant: "destructive" }); } } };
  const selectedContext = selection.map((node) => ({ id: node.id, type: node.data.nodeType, title: node.data.title, text: node.data.body, assetId: node.data.assetId || undefined, includeInAiContext: node.data.includeInContext, metadata: { status: node.data.status } }));
  const selectedAsset = selection.length === 1 && selection[0].data.assetId ? assets.find((asset) => asset.id === selection[0].data.assetId) : undefined;
  const applyDecision = async (decision: CreativeDecision) => { if (!canvas || selection.length !== 1) return; const node = selection[0]; try { await createDecision.mutateAsync({ projectId: canvas.project_id, canvasId: canvas.id, orgId: canvas.org_id, targetType: node.data.assetId ? "asset" : "shape", targetId: node.data.assetId || node.id, decision }); updateNodeData(node.id, { status: decision }); toast({ description: `Marked ${decision.replace(/_/g, " ")}.` }); } catch (error) { toast({ title: "Decision was not recorded", description: error instanceof Error ? error.message : "Try again.", variant: "destructive" }); } };
  const runGeneration = async () => { if (!canvas || !instruction.trim()) return; const point = canvasCenter(); const originalInstruction = instruction.trim(); const placeholderId = addNode("generation", { title: AI_ACTIONS.find((item) => item.value === operation)?.label ?? "AI generation", body: `Provider: ${provider}\n\n${originalInstruction}`, status: "processing", width: 360, height: 240 }, point); try { const referenceAssetIds = selection.filter((node) => ["image", "reference"].includes(node.data.nodeType) && node.data.assetId).map((node) => node.data.assetId); const result = await generate.mutateAsync({ projectId: canvas.project_id, canvasId: canvas.id, orgId: canvas.org_id, operation, instruction: originalInstruction, provider, idempotencyKey: makeIdempotencyKey(canvas.id, operation), selectedNodes: selectedContext, brandContext: brandDraft, referenceAssetIds, language, placement: point }); setNodes((current) => current.filter((node) => node.id !== placeholderId)); if (result.asset?.signedUrl) addNode("image", { title: "Generated image", body: originalInstruction, assetId: result.asset.id, assetUrl: result.asset.signedUrl, status: "generated", width: 480, height: 420 }, point); else addNode("conversation", { title: AI_ACTIONS.find((item) => item.value === operation)?.label ?? "AI response", body: `Instruction\n${originalInstruction}\n\nResponse\n${result.generation.output_text ?? "Generation completed."}`, status: "generated", width: 420, height: 320 }, point); setInstruction(""); if (result.budget?.warning) toast({ title: "Canvas AI budget warning", description: `$${result.budget.monthTotalUsd.toFixed(2)} estimated this month of a $${result.budget.softLimitUsd.toFixed(2)} soft limit.` }); } catch (error) { updateNodeData(placeholderId, { status: "failed", body: `${originalInstruction}\n\n${error instanceof Error ? error.message : "Generation failed"}` }); toast({ title: "Generation failed", description: error instanceof Error ? error.message : "Try again.", variant: "destructive" }); } };
  const exportSelection = async (format: "png" | "pdf") => { if (!selection.length) { toast({ description: "Select one or more objects to export." }); return; } const viewportElement = document.querySelector<HTMLElement>(".creative-flow-wrap .react-flow__viewport"); if (!viewportElement) return; setExporting(format); try { const ids = new Set(selection.map((node) => node.id)); let expanded = true; while (expanded) { expanded = false; nodes.forEach((node) => { if (node.parentId && ids.has(node.parentId) && !ids.has(node.id)) { ids.add(node.id); expanded = true; } }); } const exportedNodes = nodes.filter((node) => ids.has(node.id)); const bounds = getNodesBounds(exportedNodes); const width = Math.min(2400, Math.max(640, Math.ceil(bounds.width + 120))); const height = Math.min(1800, Math.max(480, Math.ceil(bounds.height + 120))); const transform = getViewportForBounds(bounds, width, height, .25, 2, .08); const edgeIds = new Set(edges.filter((edge) => ids.has(edge.source) && ids.has(edge.target)).map((edge) => edge.id)); const dataUrl = await toPng(viewportElement, { cacheBust: true, backgroundColor: "#191617", width, height, pixelRatio: 2, style: { width: `${width}px`, height: `${height}px`, transform: `translate(${transform.x}px, ${transform.y}px) scale(${transform.zoom})` }, filter: (element) => { const html = element as HTMLElement; if (html.classList?.contains("react-flow__node")) return ids.has(html.dataset.id ?? ""); if (html.classList?.contains("react-flow__edge")) return edgeIds.has(html.dataset.id ?? ""); return true; } }); const blob = await (await fetch(dataUrl)).blob(); const name = canvas?.projects.name ?? "creative-direction"; if (format === "png") downloadBlob(blob, `${name}.png`); else { const orientation = width >= height ? "landscape" : "portrait"; const pdf = new jsPDF({ orientation, unit: "px", format: [width, height] }); pdf.addImage(dataUrl, "PNG", 0, 0, width, height); pdf.save(`${name}.pdf`); } } catch (error) { toast({ title: "Export failed", description: error instanceof Error ? error.message : "Try again.", variant: "destructive" }); } finally { setExporting(null); } };

  if (isLoading) return <div className="flex h-screen items-center justify-center bg-[#171415] text-white"><Loader2 className="animate-spin text-[#CB2039]" /></div>;
  if (isError || !canvas) return <div className="flex h-screen flex-col items-center justify-center gap-4"><p className="font-medium">Canvas not found or access denied.</p><Button asChild variant="outline"><Link to="/dashboard/creative-canvas">Back to projects</Link></Button></div>;

  return <div className="creative-canvas-shell" onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); if (!flow || !event.dataTransfer.files.length) return; void upload(event.dataTransfer.files, flow.screenToFlowPosition({ x: event.clientX, y: event.clientY })); }}>
    <header className="creative-canvas-topbar"><div className="flex min-w-0 items-center gap-3"><Button asChild size="icon" variant="ghost" className="text-white/70 hover:bg-white/10 hover:text-white"><Link to="/dashboard/creative-canvas" aria-label="Back to Canvas projects"><ArrowLeft size={17} /></Link></Button><div className="h-5 w-px bg-white/10" /><div className="min-w-0"><p className="truncate text-sm font-semibold text-white">{canvas.projects.name}</p><p className="truncate text-[11px] text-white/45">{canvas.projects.client_name || "LV Branding internal"} · {canvas.name}</p></div></div><div className="flex items-center gap-2"><span className={`creative-save-state creative-save-state--${saveState}`}>{saveState === "saving" ? <Loader2 size={12} className="animate-spin" /> : saveState === "offline" ? <WifiOff size={12} /> : saveState === "error" ? <CloudOff size={12} /> : saveState === "saved" ? <Cloud size={12} /> : <Save size={12} />}{saveState}</span><Button size="sm" variant="ghost" className="text-white/70" title="Export selected content as a 2× PNG" disabled={Boolean(exporting)} onClick={() => void exportSelection("png")}>{exporting === "png" ? <Loader2 size={14} className="mr-1.5 animate-spin" /> : <Download size={14} className="mr-1.5" />}PNG</Button><Button size="sm" className="bg-[#CB2039]" title="Export selected content as a PDF with a 2× raster render" disabled={Boolean(exporting)} onClick={() => void exportSelection("pdf")}>{exporting === "pdf" && <Loader2 size={14} className="mr-1.5 animate-spin" />}Export PDF</Button></div></header>
    <div className="creative-canvas-stage">
      <aside className={`creative-toolbar ${leftOpen ? "creative-toolbar--open" : ""}`}><button className="creative-panel-toggle" onClick={() => setLeftOpen(!leftOpen)} aria-label={leftOpen ? "Collapse creation toolbar" : "Open creation toolbar"}>{leftOpen ? <ChevronLeft size={16} /> : <ChevronRight size={16} />}</button>{leftOpen && <div className="space-y-1 p-2"><p className="px-2 pb-2 pt-1 text-[10px] font-semibold uppercase tracking-[.16em] text-white/35">Create</p>{NODE_TOOLS.map(({ type, label, icon: Icon }) => <button key={type} className="creative-tool-button" onClick={() => addNode(type)}><Icon size={16} /><span>{label}</span></button>)}<button className="creative-tool-button" onClick={() => fileInput.current?.click()}><Upload size={16} /><span>Upload</span></button><input ref={fileInput} className="sr-only" type="file" accept="image/png,image/jpeg,image/webp" multiple onChange={(event) => event.target.files && void upload(event.target.files)} /><div className="my-2 h-px bg-white/10" /><button className="creative-tool-button" onClick={() => void flow?.fitView({ nodes: selection, padding: .25, duration: 250 })}><Focus size={16} /><span>Fit selection</span></button><button className="creative-tool-button" onClick={() => void flow?.fitView({ padding: .15, duration: 250 })}><Maximize2 size={16} /><span>Fit canvas</span></button></div>}</aside>
      {selection.length > 0 && <div className="creative-selection-actions"><span className="max-w-40 truncate text-xs text-white/55">{selection.length === 1 ? selection[0].data.title : `${selection.length} selected`}</span><Button size="icon" variant="ghost" className="h-8 w-8" title="Group" disabled={selection.length < 2} onClick={groupSelection}><Group size={14} /></Button><Button size="icon" variant="ghost" className="h-8 w-8" title="Ungroup" onClick={ungroupSelection}><Ungroup size={14} /></Button><Button size="icon" variant="ghost" className="h-8 w-8" title="Bring forward" onClick={() => changeOrder(1)}><ArrowUpToLine size={14} /></Button><Button size="icon" variant="ghost" className="h-8 w-8" title="Send backward" onClick={() => changeOrder(-1)}><ArrowDownToLine size={14} /></Button>{selection.length === 1 && <Select value={["favorite","shortlisted","rejected","needs_revision","client_selected","approved_final"].includes(selection[0].data.status) ? selection[0].data.status : undefined} onValueChange={(value) => void applyDecision(value as CreativeDecision)}><SelectTrigger className="h-8 w-36 border-white/10 bg-white/5 text-xs text-white"><SelectValue placeholder="Set decision" /></SelectTrigger><SelectContent><SelectItem value="favorite">Favorite</SelectItem><SelectItem value="shortlisted">Shortlisted</SelectItem><SelectItem value="needs_revision">Needs revision</SelectItem><SelectItem value="rejected">Rejected</SelectItem><SelectItem value="client_selected">Client selected</SelectItem><SelectItem value="approved_final">Approved final</SelectItem></SelectContent></Select>}{selectedAsset?.signedUrl && <Button size="sm" variant="ghost" className="h-8 text-white/65" onClick={async () => { try { const response = await fetch(selectedAsset.signedUrl!); downloadBlob(await response.blob(), selectedAsset.original_filename); } catch { toast({ title: "Download failed", variant: "destructive" }); } }}><Download size={13} className="mr-1.5" />Original</Button>}</div>}
      <main className="creative-flow-wrap"><CreativeNodeActionsProvider updateNodeData={updateNodeData}><ReactFlow<CreativeFlowNode, CreativeFlowEdge> nodes={nodes} edges={edges} nodeTypes={creativeNodeTypes} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} onConnect={connect} onInit={(instance) => { setFlow(instance); void instance.setViewport(viewportRef.current); }} onNodeDragStart={recordHistory} onMoveEnd={(_, viewport) => { viewportRef.current = viewport; if (hydrated.current) { setPendingScene(flowToScene(nodesRef.current, edgesRef.current, viewport)); setSaveState(navigator.onLine ? "unsaved" : "offline"); } }} deleteKeyCode={null} multiSelectionKeyCode={["Meta", "Control"]} selectionOnDrag panOnDrag={[1, 2]} minZoom={.1} maxZoom={4} fitViewOptions={{ padding: .15 }}><Background variant={BackgroundVariant.Dots} gap={20} size={1} color="rgba(255,255,255,.14)" /><Controls position="bottom-left" /><MiniMap position="bottom-right" pannable zoomable nodeColor={(node) => String(node.data.accent)} maskColor="rgba(23,20,21,.76)" /></ReactFlow></CreativeNodeActionsProvider>{nodes.length === 0 && <div className="creative-empty-state"><div className="creative-empty-mark"><Sparkles size={22} /></div><h2>Begin with direction, not decoration.</h2><p>Build a brief, upload the right references, then turn strategy into creative work.</p><div><Button size="sm" onClick={() => addNode("brand_context")}><Plus size={14} className="mr-1.5" />Add project brief</Button><Button size="sm" variant="outline" onClick={() => fileInput.current?.click()}><Upload size={14} className="mr-1.5" />Upload references</Button><Button size="sm" variant="outline" onClick={() => addNode("creative_direction")}><Sparkles size={14} className="mr-1.5" />Creative direction</Button></div></div>}</main>
      <aside className={`creative-inspector ${rightOpen ? "creative-inspector--open" : ""}`}><button className="creative-panel-toggle creative-panel-toggle--right" onClick={() => setRightOpen(!rightOpen)} aria-label={rightOpen ? "Collapse inspector" : "Open inspector"}>{rightOpen ? <ChevronRight size={16} /> : <ChevronLeft size={16} />}</button>{rightOpen && <Tabs defaultValue="properties" className="flex h-full flex-col"><TabsList className="m-2 grid grid-cols-4 bg-white/5"><TabsTrigger value="properties">Object</TabsTrigger><TabsTrigger value="brand">Brand</TabsTrigger><TabsTrigger value="assets">Assets</TabsTrigger><TabsTrigger value="history">History</TabsTrigger></TabsList><ScrollArea className="flex-1"><TabsContent value="properties" className="m-0 p-4">{selection.length === 1 ? <div className="space-y-4"><div><p className="creative-inspector-label">Selected object</p><p className="mt-1 text-sm font-medium capitalize text-white">{selection[0].data.nodeType.replaceAll("_", " ")}</p></div><div className="space-y-1.5"><Label className="text-white/70">Title</Label><Input value={selection[0].data.title} onChange={(event) => updateNodeData(selection[0].id, { title: event.target.value })} /></div><div className="space-y-1.5"><Label className="text-white/70">Content</Label><Textarea className="min-h-32" value={selection[0].data.body} onChange={(event) => updateNodeData(selection[0].id, { body: event.target.value })} /></div></div> : <div className="py-10 text-center text-sm text-white/45">{selection.length ? `${selection.length} objects selected` : "Select an object to edit its content and properties."}</div>}</TabsContent>
        <TabsContent value="brand" className="m-0 space-y-4 p-4"><div><p className="text-sm font-semibold text-white">Project source of truth</p><p className="mt-1 text-xs leading-5 text-white/45">Only relevant fields and selected objects are sent to AI providers.</p></div>{BRAND_FIELDS.map((field) => <div key={field.key} className="space-y-1.5"><Label className="text-xs text-white/65">{field.label}</Label><Textarea value={brandDraft[field.key] ?? ""} placeholder={field.placeholder} className="min-h-16 bg-white/5 text-xs text-white" onChange={(event) => setBrandDraft((current) => ({ ...current, [field.key]: event.target.value }))} /></div>)}<Button className="w-full bg-[#CB2039]" disabled={saveBrand.isPending} onClick={async () => { try { await saveBrand.mutateAsync(brandDraft); toast({ description: "Brand context saved." }); } catch (error) { toast({ title: "Brand context was not saved", description: error instanceof Error ? error.message : "Try again.", variant: "destructive" }); } }}>{saveBrand.isPending && <Loader2 size={14} className="mr-2 animate-spin" />}Save brand context</Button></TabsContent>
        <TabsContent value="assets" className="m-0 space-y-3 p-4"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-white">Asset library</p><p className="text-xs text-white/45">Private · {assets.length} assets</p></div><Button size="icon" variant="outline" onClick={() => fileInput.current?.click()} aria-label="Upload asset"><Plus size={14} /></Button></div>{assets.length === 0 ? <p className="py-10 text-center text-xs text-white/40">No uploaded or generated assets.</p> : <div className="grid grid-cols-2 gap-2">{assets.map((asset) => <button key={asset.id} className="overflow-hidden rounded-lg border border-white/10 bg-white/5 text-left" onClick={() => addNode(asset.source_type === "reference" ? "reference" : "image", { title: asset.original_filename, body: `${asset.source_type} asset`, assetId: asset.id, assetUrl: asset.signedUrl ?? "", width: 360, height: 340 })}>{asset.signedUrl ? <img src={asset.signedUrl} alt="" className="aspect-square w-full object-cover" /> : <div className="aspect-square bg-white/5" />}<p className="truncate p-2 text-[10px] text-white/60">{asset.original_filename}</p></button>)}</div>}</TabsContent>
        <TabsContent value="history" className="m-0 space-y-3 p-4"><div className="rounded-lg border border-white/10 bg-white/5 p-3"><div className="flex items-center gap-2 text-xs text-white/60"><CircleDollarSign size={14} className="text-[#CB2039]" />Estimated project usage</div><p className="mt-1 text-xl font-semibold text-white">${(usage?.total ?? 0).toFixed(4)}</p><p className="text-[10px] text-white/35">Estimates may differ from provider billing.</p></div>{generations.length === 0 ? <p className="py-10 text-center text-xs text-white/40">No generations yet.</p> : generations.map((item) => <div key={item.id} className="rounded-lg border border-white/10 bg-white/[.03] p-3"><div className="flex items-center justify-between"><Badge variant="outline" className="border-white/15 text-[10px] text-white/65">{item.provider}</Badge><span className={`text-[10px] ${item.status === "failed" ? "text-red-400" : "text-white/40"}`}>{item.status}</span></div><p className="mt-2 line-clamp-2 text-xs text-white/75">{item.original_instruction}</p><div className="mt-2 flex justify-between text-[10px] text-white/35"><span>{item.model}</span><span>${Number(item.estimated_cost_usd ?? 0).toFixed(4)}</span></div>{item.error_message && <p className="mt-2 text-[10px] text-red-400">{item.error_message}</p>}</div>)}</TabsContent></ScrollArea></Tabs>}</aside>
      <section className="creative-ai-bar"><div className="flex items-center gap-2 border-r border-white/10 pr-3"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#CB2039]"><Bot size={16} /></div><div><p className="text-xs font-semibold text-white">LV Intelligence</p><p className="text-[10px] text-white/40">{selection.length ? `${selection.length} selected` : "Project context"}</p></div></div><Select value={operation} onValueChange={(value) => setOperation(value as CreativeOperation)}><SelectTrigger className="h-9 w-[170px] border-white/10 bg-white/5 text-xs text-white"><SelectValue /></SelectTrigger><SelectContent>{AI_ACTIONS.map((action) => <SelectItem key={action.value} value={action.value}>{action.label}</SelectItem>)}</SelectContent></Select><Input className="h-9 min-w-52 flex-1 border-white/10 bg-white/5 text-xs text-white placeholder:text-white/30" value={instruction} onChange={(event) => setInstruction(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && (event.metaKey || event.ctrlKey)) void runGeneration(); }} placeholder="Direct the next strategic or creative move…" /><Select value={provider} onValueChange={(value) => setProvider(value as CreativeProvider)}><SelectTrigger className="h-9 w-[128px] border-white/10 bg-white/5 text-xs text-white"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="auto">Auto</SelectItem>{(["openai","google","anthropic"] as const).map((id) => { const status = providerStatus.find((item) => item.id === id); return <SelectItem key={id} value={id} disabled={status ? !status.enabled : false}>{id === "anthropic" ? "Claude" : id === "openai" ? "OpenAI" : "Google"}{status && !status.enabled ? " · off" : ""}</SelectItem>; })}</SelectContent></Select><Button size="sm" className="h-9 bg-[#CB2039]" disabled={!instruction.trim() || generate.isPending || saveState === "offline"} onClick={() => void runGeneration()}>{generate.isPending ? <Loader2 size={14} className="animate-spin" /> : <Sparkles size={14} />}<span className="ml-1.5">Create</span></Button></section>
    </div>
  </div>;
}
