import { UGC_COMMANDS } from "./ugc";
import { ASPECT_INPUT, countInput, type CommandCategory, type CommandDefinition, type CommandSafety, type CommandValues } from "./types";

/**
 * Every command LV Creative Canvas knows about.
 *
 * Ten are built and tested. The rest are registered as the roadmap so the
 * palette shows where this is going, and are refused if anything tries to run
 * them. A command that looks available and then does nothing is worse than one
 * that says it is not ready.
 */

const text = (value: unknown) => String(value ?? "").trim();

/**
 * The standing rules for anything depicting a real person.
 *
 * Carried in the instruction itself rather than left to the model's discretion,
 * and repeated per command because a single system line is easy to lose in a
 * long prompt.
 */
const PERSON_RULES = [
  "This is a visual styling simulation, not a photograph of something that happened.",
  "Work only from what is visible: garment fit, proportion, colour, texture and styling.",
  "Do not infer or comment on ethnicity, health, disability, religion, sexual orientation or personality.",
  "Do not rate attractiveness and do not make negative judgements about the person's body or face.",
  "Preserve the person's face, skin and identity exactly as they appear. Never beautify or reshape them.",
].join(" ");

const NO_TEXT = "Do not add text, watermarks, logos or captions unless the instruction asks for them.";

/** A roadmap entry: listed and searchable, never runnable. */
const soon = (
  trigger: string,
  category: CommandCategory,
  name: string,
  description: string,
  options: { aliases?: string[]; safety?: CommandSafety } = {},
): CommandDefinition => ({
  id: trigger,
  trigger,
  aliases: options.aliases ?? [],
  category,
  name,
  description,
  selection: null,
  inputs: [],
  operation: "campaign_concept",
  providers: ["auto"],
  output: "text",
  placement: "beside_source",
  cost: "low",
  confirm: true,
  safety: options.safety ?? "standard",
  status: "coming_soon",
});

// ── Built and tested ────────────────────────────────────────────────────────

const LIVE: CommandDefinition[] = [
  {
    id: "outfittransfer",
    trigger: "outfittransfer",
    aliases: ["outfit", "clothingswap", "dressme", "wardrobeswap"],
    category: "people",
    name: "Outfit transfer",
    description: "Put the outfit from a reference onto your subject, keeping the person unchanged.",
    selection: {
      types: ["image", "reference", "generation"], min: 2, max: 2, requiresArtwork: true,
      label: "Subject photo, then outfit reference",
      roles: ["Subject photo — the person to keep", "Outfit reference — the clothing to transfer"],
    },
    inputs: [
      { key: "preserve", label: "Must stay unchanged", type: "textarea", defaultValue: "Face, hair, pose, body and background", required: true,
        help: "Everything named here is protected. The clothing is all that changes." },
      { key: "notes", label: "Anything else about the outfit", type: "textarea", placeholder: "Tuck the shirt, sleeves rolled, keep the belt visible…" },
      countInput(1, 4, "Versions"),
      { ...ASPECT_INPUT, defaultValue: "portrait" },
    ],
    operation: "edit_image",
    providers: ["auto", "openai"],
    output: "image_set",
    placement: "beside_source",
    cost: "medium",
    confirm: true,
    safety: "person_likeness",
    status: "live",
    runs: (values) => Number(values.count ?? 1),
    instruction: (values) => [
      `Keep the person from the first image exactly as they are — ${text(values.preserve) || "face, hair, pose, body and background"} must be identical.`,
      "Replace only their clothing with the outfit worn in the second image: match its colour, fabric, cut, length, drape and detailing.",
      "The result is a single photograph of the person from the first image. The second image is a clothing reference only — it must not appear in the output.",
      text(values.notes),
      NO_TEXT,
      PERSON_RULES,
    ].filter(Boolean).join("\n\n"),
  },
  {
    id: "lookbook",
    trigger: "lookbook",
    aliases: ["looks", "editorial", "styleset"],
    category: "people",
    name: "Lookbook",
    description: "Build a set of coordinated looks on one subject and group them into a frame.",
    selection: {
      types: ["image", "reference", "generation"], min: 1, max: 1, requiresArtwork: true,
      label: "Subject photo", roles: ["Subject photo — the person to style"],
    },
    inputs: [
      { key: "occasion", label: "Occasion or context", type: "text", required: true, placeholder: "Founder press day, resort weekend, gallery opening…" },
      { key: "direction", label: "Styling direction", type: "textarea", placeholder: "Palette, formality, silhouette, era, anything to avoid…" },
      countInput(4, 6, "Looks"),
      { ...ASPECT_INPUT, defaultValue: "portrait" },
    ],
    operation: "edit_image",
    providers: ["auto", "openai"],
    output: "image_set",
    placement: "frame",
    cost: "high",
    confirm: true,
    safety: "person_likeness",
    status: "live",
    runs: (values) => Number(values.count ?? 4),
    instruction: (values, context) => [
      `Restyle the person in the supplied photograph for: ${text(values.occasion)}.`,
      text(values.direction),
      "Change only clothing, footwear and accessories. Keep the person's face, hair, body and pose exactly as they are.",
      "This is one look from a coordinated set — make it clearly distinct from a plain restatement of the original outfit.",
      context.brandName ? `Brand context: ${context.brandName}.` : "",
      NO_TEXT,
      PERSON_RULES,
    ].filter(Boolean).join("\n\n"),
  },
  {
    id: "hairstyles",
    trigger: "hairstyles",
    aliases: ["hair", "haircut", "hairstyle"],
    category: "people",
    name: "Hairstyle variations",
    description: "Try different cuts and styling on the same subject.",
    selection: {
      types: ["image", "reference", "generation"], min: 1, max: 1, requiresArtwork: true,
      label: "Subject photo", roles: ["Subject photo"],
    },
    inputs: [
      { key: "direction", label: "Styles to try", type: "textarea", required: true, placeholder: "Short textured crop, grown-out fringe, slicked back…" },
      { key: "keeplength", label: "Keep the original hair colour", type: "toggle", defaultValue: true },
      countInput(3, 6, "Variations"),
      { ...ASPECT_INPUT, defaultValue: "portrait" },
    ],
    operation: "edit_image",
    providers: ["auto", "openai"],
    output: "image_set",
    placement: "grid_below",
    cost: "medium",
    confirm: true,
    safety: "person_likeness",
    status: "live",
    runs: (values) => Number(values.count ?? 3),
    instruction: (values) => [
      `Restyle only the hair of the person in the supplied photograph: ${text(values.direction)}.`,
      values.keeplength === false ? "" : "Keep the original hair colour.",
      "Keep the face, skin, expression, clothing, pose and background exactly as they are. Change nothing but the hair.",
      NO_TEXT,
      PERSON_RULES,
    ].filter(Boolean).join("\n\n"),
  },
  {
    id: "backgroundreplace",
    trigger: "backgroundreplace",
    aliases: ["background", "bgreplace", "changebackground", "newbackground"],
    category: "photography",
    name: "Replace background",
    description: "Put the subject into a different environment.",
    selection: {
      types: ["image", "reference", "generation"], min: 1, max: 2, requiresArtwork: true,
      label: "Image to edit, optionally a background reference",
      roles: ["Image to edit", "Background reference (optional)"],
    },
    inputs: [
      { key: "environment", label: "New environment", type: "textarea", required: true, placeholder: "A sunlit concrete studio, a rainy Houston street at dusk…" },
      { key: "matchlighting", label: "Relight the subject to match", type: "toggle", defaultValue: true,
        help: "Off keeps the original lighting on the subject, which can read as a cut-out." },
      countInput(1, 4, "Versions"),
      ASPECT_INPUT,
    ],
    operation: "edit_image",
    providers: ["auto", "openai"],
    output: "image_set",
    placement: "beside_source",
    cost: "medium",
    confirm: true,
    safety: "standard",
    status: "live",
    runs: (values) => Number(values.count ?? 1),
    instruction: (values) => [
      `Replace the background of the first image with: ${text(values.environment)}.`,
      "Keep the main subject exactly as it is — same shape, pose, proportions, colour and detail.",
      values.matchlighting === false
        ? "Keep the subject's original lighting untouched."
        : "Relight the subject so it sits believably in the new environment: match direction, colour temperature, contact shadows and reflected light.",
      NO_TEXT,
    ].filter(Boolean).join("\n\n"),
  },
  {
    id: "relight",
    trigger: "relight",
    aliases: ["lighting", "light", "relighting"],
    category: "photography",
    name: "Relight",
    description: "Change the light on an image without changing what is in it.",
    selection: {
      types: ["image", "reference", "generation"], min: 1, max: 1, requiresArtwork: true,
      label: "Image to relight", roles: ["Image to relight"],
    },
    inputs: [
      { key: "lighting", label: "Lighting", type: "select", required: true, defaultValue: "soft-window", options: [
        { value: "soft-window", label: "Soft window light" },
        { value: "golden-hour", label: "Golden hour, low sun" },
        { value: "hard-studio", label: "Hard studio key, crisp shadows" },
        { value: "low-key", label: "Low-key, moody, deep shadow" },
        { value: "high-key", label: "High-key, bright and even" },
        { value: "overcast", label: "Overcast, flat and neutral" },
        { value: "neon", label: "Mixed neon / practical light" },
      ] },
      { key: "notes", label: "Direction and mood", type: "textarea", placeholder: "Key from camera left, warm falloff, keep the product label readable…" },
      countInput(1, 4, "Versions"),
      ASPECT_INPUT,
    ],
    operation: "edit_image",
    providers: ["auto", "openai"],
    output: "image_set",
    placement: "beside_source",
    cost: "medium",
    confirm: true,
    safety: "standard",
    status: "live",
    runs: (values) => Number(values.count ?? 1),
    instruction: (values) => {
      const named: Record<string, string> = {
        "soft-window": "soft, directional window light with gentle falloff",
        "golden-hour": "warm low golden-hour sunlight with long shadows",
        "hard-studio": "a hard studio key light with crisp, defined shadows",
        "low-key": "low-key lighting, deep shadows and a small pool of light",
        "high-key": "high-key lighting, bright, even and almost shadowless",
        overcast: "flat neutral overcast daylight",
        neon: "mixed neon and practical light sources with coloured spill",
      };
      return [
        `Relight this image with ${named[text(values.lighting)] ?? text(values.lighting)}.`,
        text(values.notes),
        "Change only the lighting. Keep the subject, composition, framing, colours of objects and every detail exactly as they are.",
        NO_TEXT,
      ].filter(Boolean).join("\n\n");
    },
  },
  {
    id: "productshot",
    trigger: "productshot",
    aliases: ["product", "stilllife", "productphoto"],
    category: "product",
    name: "Product shot",
    description: "Put a product into a considered commercial composition.",
    selection: {
      types: ["image", "reference", "generation"], min: 1, max: 2, requiresArtwork: true,
      label: "Product image", roles: ["Product image", "Style reference (optional)"],
    },
    inputs: [
      { key: "setting", label: "Setting", type: "textarea", required: true, placeholder: "On brushed travertine, soft shadow, muted backdrop…" },
      { key: "lighting", label: "Lighting", type: "text", placeholder: "Soft top light with a single crisp highlight" },
      { key: "notes", label: "Anything that must be exact", type: "textarea", placeholder: "Label must stay legible and unaltered, keep the cap colour…" },
      countInput(2, 6, "Versions"),
      ASPECT_INPUT,
    ],
    operation: "edit_image",
    providers: ["auto", "openai"],
    output: "image_set",
    placement: "grid_below",
    cost: "medium",
    confirm: true,
    safety: "standard",
    status: "live",
    runs: (values) => Number(values.count ?? 2),
    instruction: (values) => [
      `Photograph this exact product in a new composition: ${text(values.setting)}.`,
      text(values.lighting) ? `Lighting: ${text(values.lighting)}.` : "",
      "Reproduce the product itself with total fidelity — shape, proportions, colour, material, finish and any label or marking must be unchanged and undistorted.",
      text(values.notes),
      NO_TEXT,
    ].filter(Boolean).join("\n\n"),
  },
  {
    id: "moodboard",
    trigger: "moodboard",
    aliases: ["mood", "board", "visualdirection", "moodboards"],
    category: "brand",
    name: "Mood board",
    description: "Generate a set of images that establish one visual direction, grouped into a frame.",
    selection: {
      types: [], min: 0, max: 4,
      label: "Optional references to steer the direction",
    },
    inputs: [
      { key: "theme", label: "The direction", type: "textarea", required: true, placeholder: "Quiet luxury, warm concrete and linen, Houston light, no people…" },
      { key: "avoid", label: "Keep out", type: "text", placeholder: "Stock-photo smiles, neon, clutter…" },
      countInput(6, 9, "Frames"),
      ASPECT_INPUT,
    ],
    operation: "generate_image",
    providers: ["auto", "openai"],
    output: "image_set",
    placement: "frame",
    cost: "high",
    confirm: true,
    safety: "standard",
    status: "live",
    runs: (values) => Number(values.count ?? 6),
    instruction: (values, context) => [
      `One frame from a mood board establishing this direction: ${text(values.theme)}.`,
      "Make this frame a distinct facet of the direction — a different subject, scale or texture from a literal restatement of the brief.",
      text(values.avoid) ? `Avoid: ${text(values.avoid)}.` : "",
      context.brandName ? `Brand: ${context.brandName}.` : "",
      NO_TEXT,
    ].filter(Boolean).join("\n\n"),
  },
  {
    id: "creativecritique",
    trigger: "creativecritique",
    aliases: ["critique", "review", "feedback", "analyze"],
    category: "brand",
    name: "Creative critique",
    description: "An evidence-based review of selected work against the brief.",
    selection: {
      types: [], min: 1,
      label: "Work to review",
    },
    inputs: [
      { key: "criteria", label: "What to judge it against", type: "textarea",
        placeholder: "Leave empty to use the project brief and brand context." },
      { key: "audience", label: "Audience", type: "text", placeholder: "Who this has to land with" },
    ],
    operation: "visual_critique",
    providers: ["auto", "anthropic", "openai"],
    output: "text",
    placement: "beside_source",
    cost: "low",
    confirm: false,
    safety: "standard",
    status: "live",
    instruction: (values) => [
      "Review the selected work as a creative director would before it goes to a client.",
      text(values.criteria) ? `Judge it against: ${text(values.criteria)}.` : "Judge it against the supplied brief and brand context.",
      text(values.audience) ? `Audience: ${text(values.audience)}.` : "",
      "Be specific and evidence-based: point at what is actually in the work. Say what is working, what is not, and what you would change first. No praise that could apply to anything.",
    ].filter(Boolean).join("\n\n"),
  },
  {
    id: "headline",
    trigger: "headline",
    aliases: ["headlines", "hed", "title"],
    category: "copy",
    name: "Headlines",
    description: "Write or sharpen headlines for a campaign or page.",
    selection: { types: [], min: 0, label: "Optional context to write from" },
    inputs: [
      { key: "brief", label: "What it has to do", type: "textarea", required: true, placeholder: "Announce the studio's move into hospitality branding…" },
      { key: "tone", label: "Tone", type: "select", defaultValue: "confident", options: [
        { value: "confident", label: "Confident, plain" },
        { value: "warm", label: "Warm, human" },
        { value: "bold", label: "Bold, declarative" },
        { value: "editorial", label: "Editorial, considered" },
        { value: "playful", label: "Playful" },
      ] },
      countInput(6, 12, "Options"),
    ],
    operation: "write_copy",
    providers: ["auto", "anthropic", "openai"],
    output: "text",
    placement: "beside_source",
    cost: "low",
    confirm: false,
    safety: "standard",
    status: "live",
    instruction: (values) => [
      `Write ${Number(values.count ?? 6)} headline options. What they have to do: ${text(values.brief)}.`,
      `Tone: ${text(values.tone) || "confident"}.`,
      "Number them. Keep each one short enough to set large. No subheads, no explanation, no repetition of the same idea in different words.",
    ].join("\n\n"),
  },
  {
    id: "bilingualadapt",
    trigger: "bilingualadapt",
    aliases: ["translate", "spanish", "english", "adapt", "bilingual"],
    category: "copy",
    name: "Bilingual adaptation",
    description: "Carry meaning between English and Spanish markets rather than translating literally.",
    selection: { types: [], min: 1, label: "Copy to adapt" },
    inputs: [
      { key: "direction", label: "Direction", type: "select", required: true, defaultValue: "en_es", options: [
        { value: "en_es", label: "English → Spanish" },
        { value: "es_en", label: "Spanish → English" },
      ] },
      { key: "market", label: "Market", type: "text", placeholder: "US Hispanic, Mexico, Spain, Houston…" },
      { key: "notes", label: "Anything to hold onto", type: "textarea", placeholder: "Keep the pun if it survives, keep the brand name in English…" },
    ],
    operation: "adapt_en_es",
    resolveOperation: (values) => (values.direction === "es_en" ? "adapt_es_en" : "adapt_en_es"),
    providers: ["auto", "anthropic", "openai"],
    output: "text",
    placement: "beside_source",
    cost: "low",
    confirm: false,
    safety: "standard",
    status: "live",
    instruction: (values) => [
      "Adapt the selected copy for the other market. Preserve intent, positioning, voice and cultural fit — do not translate word for word.",
      text(values.market) ? `Market: ${text(values.market)}.` : "",
      text(values.notes),
      "Where a phrase cannot carry over, write the version that does the same job and note in one line what you changed and why.",
    ].filter(Boolean).join("\n\n"),
  },
];

// ── Registered roadmap ──────────────────────────────────────────────────────

const ROADMAP: CommandDefinition[] = [
  // People & Style
  soon("outfitstyles", "people", "Outfit directions", "Outfit directions for an occasion, profession or aesthetic.", { safety: "person_likeness" }),
  soon("stylebook", "people", "Style book", "A personalised style guide built from references.", { safety: "person_likeness" }),
  soon("glassestryon", "people", "Eyewear try-on", "Visualise eyewear alternatives.", { safety: "person_likeness" }),
  soon("haircolor", "people", "Hair colour", "Test natural or creative hair colours.", { aliases: ["haircolour"], safety: "person_likeness" }),
  soon("beardstyles", "people", "Beard styles", "Explore beard and facial-hair variations.", { safety: "person_likeness" }),
  soon("groomingstyles", "people", "Grooming", "Broader grooming recommendations.", { safety: "person_likeness" }),
  soon("coloranalysis", "people", "Colour analysis", "An appearance-based colour palette.", { aliases: ["colouranalysis"], safety: "person_likeness" }),
  soon("fitprofile", "people", "Fit profile", "Garment cuts and proportions from stated preferences and visible fit.", { aliases: ["bodytype"], safety: "person_likeness" }),
  soon("facestylingmap", "people", "Face styling map", "Eyewear, hair and grooming shapes from visible facial geometry.", { aliases: ["faceanalysis"], safety: "person_likeness" }),
  soon("styleprofile", "people", "Style profile", "A reusable personal-style context.", { safety: "person_likeness" }),
  soon("wardrobe", "people", "Wardrobe", "Organise uploaded clothing into a visual wardrobe.", { safety: "person_likeness" }),
  soon("wardrobeaudit", "people", "Wardrobe audit", "Coverage, repetition and gaps in a wardrobe.", { safety: "person_likeness" }),
  soon("capsulewardrobe", "people", "Capsule wardrobe", "A limited, coordinated wardrobe.", { safety: "person_likeness" }),
  soon("closetupgrade", "people", "Closet upgrade", "Strategic additions to an existing wardrobe.", { safety: "person_likeness" }),
  soon("occasionlook", "people", "Occasion look", "A look for a specific event.", { safety: "person_likeness" }),
  soon("professionallook", "people", "Professional look", "Wardrobe options for professional positioning.", { safety: "person_likeness" }),
  soon("brandambassadorlook", "people", "Ambassador look", "Align a person's appearance with a brand or campaign.", { safety: "person_likeness" }),
  soon("accessorystyles", "people", "Accessories", "Watches, jewellery, ties, scarves and other accessories.", { safety: "person_likeness" }),
  soon("shoestyles", "people", "Footwear", "Footwear recommendations.", { safety: "person_likeness" }),
  soon("outfitvariations", "people", "Outfit variations", "Controlled alternatives from one approved look.", { safety: "person_likeness" }),
  soon("seasonalwardrobe", "people", "Seasonal wardrobe", "Wardrobe adapted by season and location.", { safety: "person_likeness" }),
  soon("packinglist", "people", "Packing list", "A visual travel wardrobe and packing plan.", { safety: "person_likeness" }),

  // Photography
  soon("backgroundremove", "photography", "Remove background", "Create a transparent-background asset.", { aliases: ["cutout", "transparent"] }),
  soon("colorgrade", "photography", "Colour grade", "Apply a controlled photographic treatment.", { aliases: ["colourgrade", "grade"] }),
  soon("retouch", "photography", "Retouch", "Non-destructive commercial retouching.", { safety: "person_likeness" }),
  soon("cleanup", "photography", "Clean up", "Remove distractions and imperfections."),
  soon("removeobject", "photography", "Remove object", "Remove a selected object.", { aliases: ["erase"] }),
  soon("replaceobject", "photography", "Replace object", "Replace an object using a reference or instruction."),
  soon("inpaint", "photography", "Inpaint", "Modify a selected region of an image."),
  soon("outpaint", "photography", "Outpaint", "Extend an image beyond its current boundaries.", { aliases: ["extend"] }),
  soon("reframe", "photography", "Reframe", "Adapt composition to a new aspect ratio.", { aliases: ["crop"] }),
  soon("compositionvariants", "photography", "Composition variants", "Alternative framing and camera placement."),
  soon("depthoffield", "photography", "Depth of field", "Simulate a different depth-of-field treatment.", { aliases: ["bokeh"] }),
  soon("daytonight", "photography", "Day to night", "Transform environmental time and lighting."),
  soon("weatherchange", "photography", "Weather", "Change atmospheric or weather conditions."),
  soon("restoration", "photography", "Restore", "Restore a damaged or aged photograph.", { aliases: ["restore"] }),
  soon("upscale", "photography", "Upscale", "Prepare a larger production-ready version.", { aliases: ["enlarge"] }),
  soon("stylematch", "photography", "Style match", "Match the visual treatment of a reference."),
  soon("subjectisolate", "photography", "Isolate subject", "Separate a subject from the scene."),
  soon("contactsheet", "photography", "Contact sheet", "Arrange selected images into a review sheet."),
  soon("selectbest", "photography", "Select best", "Critique selected images against the project brief."),
  soon("shotlist", "photography", "Shot list", "The missing photographs a campaign still needs."),

  // Product & Commercial
  soon("packshot", "product", "Packshot", "A clean catalogue-style presentation."),
  soon("productscene", "product", "Product scene", "Place a product into a controlled environment."),
  soon("lifestylescene", "product", "Lifestyle scene", "A product in a natural usage situation."),
  soon("productangles", "product", "Product angles", "Alternate product viewpoints."),
  soon("productvariations", "product", "Product variations", "Controlled creative treatments."),
  soon("materialswap", "product", "Material swap", "Visualise different finishes or materials."),
  soon("colorswap", "product", "Colourway", "Generate product colourways.", { aliases: ["colourswap", "colorway"] }),
  soon("labelconcept", "product", "Label concept", "Explore label applications."),
  soon("packagingconcept", "product", "Packaging concept", "Develop packaging directions."),
  soon("mockup", "product", "Mockup", "Apply approved artwork to a mockup."),
  soon("menuvisual", "product", "Menu visual", "Commercial food or hospitality imagery."),
  soon("foodstyle", "product", "Food styling", "Plating, props and photographic styling."),
  soon("heroimage", "product", "Hero image", "A website or campaign hero composition."),
  soon("adcreative", "product", "Ad creative", "Turn a product image into advertising concepts."),
  soon("ecommercekit", "product", "E-commerce kit", "A coordinated set of product images."),
  soon("campaignset", "product", "Campaign set", "Brand context to key visual to channel variations to copy, in one frame."),

  // Brand & Campaign
  soon("creativedirections", "brand", "Creative directions", "Multiple strategic creative territories."),
  soon("brandapply", "brand", "Apply brand", "Apply the project's visual system to an asset."),
  soon("brandcheck", "brand", "Brand check", "Evaluate an asset against brand rules."),
  soon("paletteextract", "brand", "Extract palette", "Extract and organise a colour system.", { aliases: ["extractcolors"] }),
  soon("paletteexplore", "brand", "Explore palettes", "Strategic palette alternatives."),
  soon("typographypairing", "brand", "Type pairing", "Develop typography combinations.", { aliases: ["typepairing", "fonts"] }),
  soon("campaignconcepts", "brand", "Campaign concepts", "Campaign platforms and narratives."),
  soon("keyvisual", "brand", "Key visual", "A central campaign visual."),
  soon("visualsystem", "brand", "Visual system", "Expand one concept into a repeatable design language."),
  soon("socialkit", "brand", "Social kit", "A coordinated social-media asset system."),
  soon("advariations", "brand", "Ad variations", "Controlled campaign alternatives."),
  soon("formatadapt", "brand", "Format adapt", "Adapt approved artwork into channel-specific formats."),
  soon("brandpresentation", "brand", "Brand presentation", "Turn selected frames into a client presentation.", { aliases: ["presentation", "deck"] }),
  soon("compareconcepts", "brand", "Compare concepts", "Evaluate directions against strategic criteria.", { aliases: ["compare"] }),
  soon("finalartcheck", "brand", "Final art check", "Composition, copy, brand rules and production readiness.", { aliases: ["preflight"] }),

  // Copy & Strategy
  soon("tagline", "copy", "Tagline", "Brand or campaign taglines."),
  soon("caption", "copy", "Caption", "Channel-appropriate captions."),
  soon("cta", "copy", "Call to action", "Develop calls to action."),
  soon("adcopy", "copy", "Ad copy", "Advertising variations."),
  soon("brandvoice", "copy", "Brand voice", "Define or apply a voice system."),
  soon("positioning", "copy", "Positioning", "Positioning alternatives."),
  soon("valueproposition", "copy", "Value proposition", "Clarify the commercial value proposition.", { aliases: ["valueroposition", "valueprop"] }),
  soon("creativebrief", "copy", "Creative brief", "Build a structured creative brief.", { aliases: ["brief"] }),
  soon("rationale", "copy", "Rationale", "The strategic logic behind a direction."),
  soon("storyboard", "copy", "Storyboard", "Convert a concept or script into visual beats."),
  soon("script", "copy", "Script", "Generate or refine video scripts."),
  soon("copyvariants", "copy", "Copy variants", "Controlled alternatives."),
  soon("shorten", "copy", "Shorten", "Reduce copy while preserving intent."),
  soon("expand", "copy", "Expand", "Develop a selected idea further."),
  soon("tonechange", "copy", "Change tone", "Adjust voice without changing the message."),
  soon("proofread", "copy", "Proofread", "Correct grammar and clarity."),
  soon("contentseries", "copy", "Content series", "Expand one idea into multiple pieces."),
  soon("campaignmatrix", "copy", "Campaign matrix", "Map audience, message, channel and creative variation."),

  // Canvas & Production
  soon("arrange", "canvas", "Arrange", "Lay selected objects out on a grid."),
  soon("versions", "canvas", "Versions", "Show every version of a piece and how it got there."),
  soon("exportset", "canvas", "Export set", "Produce a delivery set at every required size."),
  soon("handoff", "canvas", "Handoff", "Assemble approved work and its rationale for a client."),
  soon("cleancanvas", "canvas", "Tidy canvas", "Find failed, orphaned and duplicate objects."),
];

export const COMMANDS: CommandDefinition[] = [...LIVE, ...UGC_COMMANDS, ...ROADMAP];

/** Commands that can actually run. */
export const liveCommands = () => COMMANDS.filter((command) => command.status === "live");

export const commandRuns = (command: CommandDefinition, values: CommandValues) =>
  Math.max(1, Math.round(command.runs?.(values) ?? 1));
