import { countInput, type CommandDefinition, type CommandSafety, type UgcMode } from "./types";

/**
 * UGC commands.
 *
 * Two modes, kept apart on purpose. `creator` content comes from a real person
 * — their experience, their words, their footage — and the system's job is to
 * shape it, never to invent it. `synthetic` content is generated, and the
 * system's job is to make sure nobody mistakes it for the first kind.
 *
 * The line between them is the whole point of this category. A fabricated
 * testimonial presented as real is not a creative shortcut, it is a false
 * statement about a customer, so the commands that touch claims require the
 * real material to be supplied and refuse to run without it.
 */

const text = (value: unknown) => String(value ?? "").trim();

/** Carried by anything that shapes a real person's account of their experience. */
const CREATOR_TRUTH = [
  "Work only from the supplied material. Do not invent experiences, results, quotes or details the creator did not provide.",
  "Where something is missing, say what is missing rather than filling it in.",
  "Keep the creator's own voice and vocabulary — this should read as them, not as an agency.",
].join(" ");

/** Carried by anything generated that a viewer could take for a real person. */
const SYNTHETIC_NOTICE = [
  "This is synthetic content. It must be presented as AI-generated and must never be described as a real customer, a real employee or a real experience.",
  "Do not write it as a testimonial, do not state outcomes as things that happened, and include the disclosure the platform requires.",
].join(" ");

/** Carried by anything that states an outcome someone could rely on. */
const CLAIM_RULES = [
  "Every claim must be traceable to the supplied evidence. Mark any claim that is not, and do not soften it into something that merely sounds safe.",
  "Flag anything touching health, finances, earnings, safety or measurable performance for human review before use.",
].join(" ");

const ugcSoon = (
  trigger: string,
  name: string,
  description: string,
  options: { aliases?: string[]; mode?: UgcMode; safety?: CommandSafety } = {},
): CommandDefinition => ({
  id: trigger,
  trigger,
  aliases: options.aliases ?? [],
  category: "ugc",
  name,
  description,
  selection: null,
  inputs: [],
  operation: "campaign_concept",
  providers: ["auto"],
  output: "text",
  placement: "beside_source",
  cost: "low",
  confirm: true,
  safety: options.safety ?? "standard",
  ugcMode: options.mode ?? "either",
  status: "coming_soon",
});

const PLATFORMS = [
  { value: "reels", label: "Instagram Reels" },
  { value: "tiktok", label: "TikTok" },
  { value: "shorts", label: "YouTube Shorts" },
  { value: "paid", label: "Paid placement" },
];

const LIVE: CommandDefinition[] = [
  {
    id: "ugcbrief",
    trigger: "ugcbrief",
    aliases: ["creatorbrief", "briefcreator"],
    category: "ugc",
    name: "Creator brief",
    description: "A production-ready brief a creator can actually shoot from.",
    selection: { types: [], min: 0, label: "Optional context — brand, product or campaign cards" },
    inputs: [
      { key: "objective", label: "What this campaign has to achieve", type: "textarea", required: true, placeholder: "Drive trial of the new lunch menu with people who already follow us…" },
      { key: "product", label: "Product or service", type: "text", required: true },
      { key: "audience", label: "Audience", type: "text", placeholder: "Who it has to land with" },
      { key: "mustsay", label: "Must say", type: "textarea", placeholder: "Non-negotiable messages, offer terms, legal lines…" },
      { key: "mustnotsay", label: "Must not say", type: "textarea", placeholder: "Claims we cannot support, competitor mentions…" },
      { key: "platform", label: "Primary platform", type: "select", defaultValue: "reels", options: PLATFORMS },
    ],
    operation: "campaign_concept",
    providers: ["auto", "anthropic", "openai"],
    output: "text",
    placement: "beside_source",
    cost: "low",
    confirm: false,
    safety: "standard",
    ugcMode: "creator",
    status: "live",
    instruction: (values, context) => [
      `Write a creator brief for: ${text(values.product)}.`,
      `Objective: ${text(values.objective)}.`,
      text(values.audience) ? `Audience: ${text(values.audience)}.` : "",
      text(values.mustsay) ? `Must say: ${text(values.mustsay)}.` : "",
      text(values.mustnotsay) ? `Must not say: ${text(values.mustnotsay)}.` : "",
      `Primary platform: ${text(values.platform) || "Instagram Reels"}.`,
      context.brandName ? `Brand: ${context.brandName}.` : "",
      "Structure it as: the one thing this has to do · what the creator should show · what they should say in their own words · what to avoid · deliverables and formats · disclosure requirement.",
      "Write it for a person with a phone, not for a production crew. Be concrete about shots and specific about what not to claim.",
      CLAIM_RULES,
    ].filter(Boolean).join("\n\n"),
  },
  {
    id: "ugchooks",
    trigger: "ugchooks",
    aliases: ["hooks", "openers", "hookbank"],
    category: "ugc",
    name: "Hooks",
    description: "Opening lines that earn the next three seconds.",
    selection: { types: [], min: 0, label: "Optional context" },
    inputs: [
      { key: "subject", label: "What the video is about", type: "textarea", required: true },
      { key: "angle", label: "Angles to cover", type: "text", placeholder: "Problem-led, demonstration, storytime, objection…" },
      countInput(10, 20, "Hooks"),
    ],
    operation: "write_copy",
    providers: ["auto", "anthropic", "openai"],
    output: "text",
    placement: "beside_source",
    cost: "low",
    confirm: false,
    safety: "standard",
    ugcMode: "either",
    status: "live",
    instruction: (values) => [
      `Write ${Number(values.count ?? 10)} opening hooks for a vertical video about: ${text(values.subject)}.`,
      text(values.angle) ? `Cover these angles: ${text(values.angle)}.` : "Vary the angle — problem, demonstration, story, objection, curiosity.",
      "Each hook is the first sentence someone says or the first line on screen. Under about twelve words. Number them and mark the angle each one uses.",
      "No clickbait that the video cannot pay off, and no claims about results.",
    ].filter(Boolean).join("\n\n"),
  },
  {
    id: "ugcscript",
    trigger: "ugcscript",
    aliases: ["creatorscript", "videoscript"],
    category: "ugc",
    name: "Creator script",
    description: "A script that sounds like a person, timed for vertical video.",
    selection: { types: [], min: 0, label: "Optional brief, hook or product context" },
    inputs: [
      { key: "subject", label: "What the video is about", type: "textarea", required: true },
      { key: "hook", label: "Opening hook, if chosen", type: "text" },
      { key: "length", label: "Length", type: "select", defaultValue: "30", options: [
        { value: "15", label: "15 seconds" }, { value: "30", label: "30 seconds" }, { value: "60", label: "60 seconds" },
      ] },
      { key: "platform", label: "Platform", type: "select", defaultValue: "reels", options: PLATFORMS },
    ],
    operation: "write_copy",
    providers: ["auto", "anthropic", "openai"],
    output: "text",
    placement: "beside_source",
    cost: "low",
    confirm: false,
    safety: "standard",
    ugcMode: "either",
    status: "live",
    instruction: (values) => [
      `Write a ${text(values.length) || "30"}-second creator script about: ${text(values.subject)}.`,
      text(values.hook) ? `Open with this hook: ${text(values.hook)}.` : "",
      `Platform: ${text(values.platform) || "Instagram Reels"}.`,
      "Lay it out as HOOK (0–3s) · BODY · PROOF · CTA, with a rough timecode on each section and the on-screen action beside the spoken line.",
      "Write how someone actually talks — contractions, short sentences, one idea at a time. No agency voice, no stacked adjectives.",
      "Mark anything that would count as a claim so it can be checked before shooting.",
    ].filter(Boolean).join("\n\n"),
  },
  {
    id: "ugctalkingpoints",
    trigger: "ugctalkingpoints",
    aliases: ["talkingpoints", "points"],
    category: "ugc",
    name: "Talking points",
    description: "Flexible points a creator can say in their own words instead of a script.",
    selection: { types: [], min: 0, label: "Optional brief or product context" },
    inputs: [
      { key: "subject", label: "What the video is about", type: "textarea", required: true },
      { key: "mustsay", label: "Must be covered", type: "textarea" },
    ],
    operation: "write_copy",
    providers: ["auto", "anthropic", "openai"],
    output: "text",
    placement: "beside_source",
    cost: "low",
    confirm: false,
    safety: "standard",
    ugcMode: "creator",
    status: "live",
    instruction: (values) => [
      `Write talking points for a creator making a vertical video about: ${text(values.subject)}.`,
      text(values.mustsay) ? `These must be covered: ${text(values.mustsay)}.` : "",
      "Points, not sentences to read out. Each one is an idea the creator puts in their own words, with a note on why it matters.",
      "Include what to avoid saying and any disclosure they must make.",
      CREATOR_TRUTH,
    ].filter(Boolean).join("\n\n"),
  },
  {
    id: "ugctestimonial",
    trigger: "ugctestimonial",
    // "review" belongs to /creativecritique; here it would mean the opposite thing.
    aliases: ["testimonial", "customerreview"],
    category: "ugc",
    name: "Testimonial structure",
    description: "Shape a real customer's account into a usable testimonial — never invent one.",
    selection: { types: [], min: 0, label: "Optional transcript or notes on the canvas" },
    inputs: [
      { key: "account", label: "The customer's actual words or account", type: "textarea", required: true,
        help: "Paste what they really said or wrote. This command shapes real material and will not invent an experience." },
      { key: "permission", label: "Who gave permission, and for what", type: "text", required: true,
        placeholder: "Name, date, and what they agreed to — organic, paid, whitelisting…" },
      { key: "focus", label: "What to bring forward", type: "text", placeholder: "The moment it clicked, the objection they had…" },
    ],
    operation: "write_copy",
    providers: ["auto", "anthropic", "openai"],
    output: "text",
    placement: "beside_source",
    cost: "low",
    confirm: true,
    safety: "attested_claim",
    ugcMode: "creator",
    status: "live",
    instruction: (values) => [
      "Shape the following real customer account into a testimonial structure for a vertical video.",
      `Their account, verbatim: ${text(values.account)}`,
      `Permission on record: ${text(values.permission)}.`,
      text(values.focus) ? `Bring forward: ${text(values.focus)}.` : "",
      "Keep their words wherever they work. Where you tighten, keep the meaning exactly — mark every line you changed and show the original beside it.",
      "Do not add detail, emotion, outcomes or specifics that are not in their account. If the account is too thin to carry a testimonial, say so and list what to go back and ask them.",
      CREATOR_TRUTH,
      CLAIM_RULES,
    ].filter(Boolean).join("\n\n"),
  },
  {
    id: "ugcavatar",
    trigger: "ugcavatar",
    aliases: ["avatar", "syntheticpresenter", "aipresenter"],
    category: "ugc",
    name: "Synthetic presenter",
    description: "A disclosed AI presenter concept — never a stand-in for a real customer.",
    selection: { types: [], min: 0, label: "Optional product or brand context" },
    inputs: [
      { key: "subject", label: "What the presenter covers", type: "textarea", required: true },
      { key: "persona", label: "Presenter persona", type: "text", placeholder: "Role and register — not a real person's likeness" },
      { key: "platform", label: "Platform", type: "select", defaultValue: "reels", options: PLATFORMS },
    ],
    operation: "campaign_concept",
    providers: ["auto", "anthropic", "openai"],
    output: "text",
    placement: "beside_source",
    cost: "low",
    confirm: true,
    safety: "synthetic_person",
    ugcMode: "synthetic",
    disclosure: "Created with AI. Not a real customer or a record of a real experience.",
    status: "live",
    instruction: (values) => [
      `Develop a synthetic presenter concept covering: ${text(values.subject)}.`,
      text(values.persona) ? `Persona: ${text(values.persona)}. This must be an invented presenter, not a likeness of any real person.` : "The presenter must be invented, not a likeness of any real person.",
      `Platform: ${text(values.platform) || "Instagram Reels"}.`,
      "Give the concept, the script, the on-screen disclosure wording and where it appears, and the caption disclosure.",
      SYNTHETIC_NOTICE,
      CLAIM_RULES,
    ].filter(Boolean).join("\n\n"),
  },
  {
    id: "ugccaption",
    trigger: "ugccaption",
    aliases: ["socialcaption", "postcaption"],
    category: "ugc",
    name: "Social caption",
    description: "The caption that runs with the video, per platform.",
    selection: { types: [], min: 0, label: "Optional script or video context" },
    inputs: [
      { key: "subject", label: "What the video is about", type: "textarea", required: true },
      { key: "platform", label: "Platform", type: "select", defaultValue: "reels", options: PLATFORMS },
      { key: "sponsored", label: "This is sponsored or gifted", type: "toggle", defaultValue: false },
    ],
    operation: "write_copy",
    providers: ["auto", "anthropic", "openai"],
    output: "text",
    placement: "beside_source",
    cost: "low",
    confirm: false,
    safety: "standard",
    ugcMode: "either",
    status: "live",
    instruction: (values) => [
      `Write the caption for a vertical video about: ${text(values.subject)}.`,
      `Platform: ${text(values.platform) || "Instagram Reels"}. Match its length and conventions.`,
      values.sponsored === true
        ? "This is sponsored or gifted: open with a clear, plain-language disclosure, not a buried hashtag."
        : "",
      "Give three options of different lengths. Hashtags only where the platform expects them, and no more than a handful.",
    ].filter(Boolean).join("\n\n"),
  },
  {
    id: "ugccta",
    trigger: "ugccta",
    aliases: ["creatorcta"],
    category: "ugc",
    name: "Creator CTA",
    description: "Calls to action a creator can say without sounding like an ad.",
    selection: { types: [], min: 0, label: "Optional script or campaign context" },
    inputs: [
      { key: "action", label: "What you want people to do", type: "text", required: true },
      { key: "offer", label: "Offer or reason to act now", type: "text" },
      countInput(6, 12, "Options"),
    ],
    operation: "write_copy",
    providers: ["auto", "anthropic", "openai"],
    output: "text",
    placement: "beside_source",
    cost: "low",
    confirm: false,
    safety: "standard",
    ugcMode: "either",
    status: "live",
    instruction: (values) => [
      `Write ${Number(values.count ?? 6)} calls to action for: ${text(values.action)}.`,
      text(values.offer) ? `Offer: ${text(values.offer)}.` : "",
      "Written to be spoken by a creator on camera — short, unforced, in their own register. Number them and note where in the video each one fits.",
      "No urgency that is not real, and no promise the offer does not make.",
    ].filter(Boolean).join("\n\n"),
  },
  {
    id: "ugccompliance",
    trigger: "ugccompliance",
    aliases: ["compliance", "claimscheck", "disclosure"],
    category: "ugc",
    name: "Compliance review",
    description: "Check claims, disclosures and usage risk before anything goes out.",
    selection: { types: [], min: 1, label: "The script, caption or transcript to review" },
    inputs: [
      { key: "evidence", label: "Evidence available for the claims", type: "textarea",
        placeholder: "What can actually be substantiated, and by what." },
      { key: "relationship", label: "Relationship with the creator", type: "select", defaultValue: "paid", options: [
        { value: "paid", label: "Paid" }, { value: "gifted", label: "Gifted product" },
        { value: "affiliate", label: "Affiliate" }, { value: "employee", label: "Employee" },
        { value: "organic", label: "Unpaid and unsolicited" },
      ] },
      { key: "market", label: "Market", type: "text", placeholder: "US, Mexico, Spain…" },
    ],
    operation: "visual_critique",
    providers: ["auto", "anthropic", "openai"],
    output: "text",
    placement: "beside_source",
    cost: "low",
    confirm: false,
    // Not `attested_claim`: this is the command that checks whether claims hold
    // up. Asking someone to swear they do before it will run would defeat it.
    safety: "standard",
    ugcMode: "either",
    status: "live",
    instruction: (values) => [
      "Review the selected content for claims, disclosure and usage risk before it is published.",
      `Creator relationship: ${text(values.relationship) || "paid"}.`,
      text(values.market) ? `Market: ${text(values.market)}.` : "",
      text(values.evidence) ? `Evidence available: ${text(values.evidence)}.` : "No evidence has been supplied — treat every factual claim as unsubstantiated.",
      "List each claim, say whether the supplied evidence supports it, and mark the ones that do not.",
      "Say what disclosure this relationship requires, in what words, and where it has to appear.",
      "Separately flag anything touching health, finances, earnings, safety or measurable performance as needing human review.",
      "You are not a lawyer and this is not legal advice — say so, and say what a person still needs to check.",
      CLAIM_RULES,
    ].filter(Boolean).join("\n\n"),
  },
  {
    id: "ugccritique",
    trigger: "ugccritique",
    aliases: ["ugcreview", "ugcfeedback"],
    category: "ugc",
    name: "UGC critique",
    description: "Judge authenticity, clarity, pace and persuasion.",
    selection: { types: [], min: 1, label: "The script, storyboard or footage notes to judge" },
    inputs: [
      { key: "objective", label: "What this has to achieve", type: "textarea" },
      { key: "platform", label: "Platform", type: "select", defaultValue: "reels", options: PLATFORMS },
    ],
    operation: "visual_critique",
    providers: ["auto", "anthropic", "openai"],
    output: "text",
    placement: "beside_source",
    cost: "low",
    confirm: false,
    safety: "standard",
    ugcMode: "either",
    status: "live",
    instruction: (values) => [
      "Judge the selected UGC against how this content actually performs.",
      text(values.objective) ? `It has to: ${text(values.objective)}.` : "",
      `Platform: ${text(values.platform) || "Instagram Reels"}.`,
      "Take each in turn: does the first three seconds earn the next ten · does it sound like a person or like an ad · is the product moment clear · does the pace hold · does the CTA follow from what came before.",
      "Point at specific lines. Say the single change that would help most, and be honest if the piece does not work.",
    ].filter(Boolean).join("\n\n"),
  },
];

const ROADMAP: CommandDefinition[] = [
  ugcSoon("ugcbroll", "B-roll", "Plan or generate supporting vertical B-roll."),
  ugcSoon("ugcproducthold", "Product hold", "A creator naturally holding the product.", { mode: "synthetic", safety: "synthetic_person" }),
  ugcSoon("ugcenvironment", "Environment", "Place the creator or product in a fitting environment."),
  ugcSoon("ugcrepurpose", "Repurpose", "One recording into 15s, 30s and 60s cuts, hooks, captions, subtitles and adaptations.", { mode: "creator" }),
  ugcSoon("ugcsubtitles", "Subtitles", "Generate and style subtitles."),
  ugcSoon("ugcresize", "Resize", "Adapt for Reels, TikTok, Shorts or paid placements."),
  ugcSoon("ugcmatrix", "Testing matrix", "Map hooks, audiences, messages, creators and CTAs onto the canvas."),
  ugcSoon("ugccampaign", "UGC campaign", "A full coordinated campaign: territories, hooks, scripts, shot lists, CTAs, both languages, organised into frames."),
];

export const UGC_COMMANDS: CommandDefinition[] = [...LIVE, ...ROADMAP];
